Install Packages and Import Libraries

In [ ]:
# %pip install -q -r ../requirements.txt

In [1]:
# Import required libraries and modules for zero-shot sampling and few-shot training.
import os
import sys
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import torch
from dotenv import load_dotenv
from huggingface_hub import HfApi, login
from IPython.display import display

warnings.filterwarnings('ignore')

project_root = Path.cwd().parent
sys.path.insert(0, str(project_root))

from src.local.classification.vlm.models import (load_openai_clip, load_biomedclip, load_unimedclip, make_openai_clip_loader, make_biomedclip_loader, make_unimedclip_loader)
from src.local.classification.vlm.helpers import (load_busi_splits, save_results_to_csv, encode_images_batch)
from src.local.classification.vlm.zero_shot import ZeroShotEvaluator
from src.local.prompting.prompt_registry import PROMPT_REGISTRY
from src.local.classification.vlm.few_shot_lp import (LinearProbeConfig, make_kshot_indices, run_linear_probe_experiments)
from src.local.classification.vlm.few_shot_lora import get_args, run_kshot_experiments

c:\Users\mason\Desktop\busi-vlm-project\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Authenticate Hugging Face and Select Device

In [2]:
load_dotenv(project_root / '.env', override=True)

huggingface_token = os.getenv('huggingface_token')
api = HfApi(token=huggingface_token) if huggingface_token else None

if huggingface_token:
    login(token=huggingface_token, add_to_git_credential=False)
    print('HuggingFace authenticated as -', api.whoami()['name'])
else:
    print('No huggingface_token found.')

HuggingFace authenticated as - masonezra34

In [3]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print('device -', device)

if device == 'cuda':
    print(torch.cuda.get_device_name(0))

device - cuda
NVIDIA GeForce RTX 5060 Laptop GPU

Define BUSI Classes and Prompt Labels

In [4]:
# Setup BUSI classes and prompts.
busi_classes = ['benign', 'malignant', 'normal']

class_mapping = {
    'benign': 'benign tumor',
    'malignant': 'malignant tumor',
    'normal': 'normal scan'
}

class_names_for_prompts = [class_mapping[c] for c in busi_classes]

print(f'BUSI classes - {busi_classes}')
print(f'prompt registry classes - {class_names_for_prompts}')
print(f'prompts per class:')

for class_name in class_names_for_prompts:
    print(f'  {class_name}: {len(PROMPT_REGISTRY[class_name])} prompts')

BUSI classes - ['benign', 'malignant', 'normal']
prompt registry classes - ['benign tumor', 'malignant tumor', 'normal scan']
prompts per class:
  benign tumor: 8 prompts
  malignant tumor: 8 prompts
  normal scan: 8 prompts

Load BUSI Train, Validation, and Test Splits

In [5]:
# Load BUSI train/val/test splits.
train_df, val_df, test_df = load_busi_splits(project_root, busi_classes)

print(f'\ndataset splits:')
print(f'* train - {len(train_df)}')
print(f'* validation - {len(val_df)}')
print(f'* test - {len(test_df)}')
print(f'\ntest distribution:')
print(test_df['label'].value_counts())

dataset splits:
* train - 437
* validation - 93
* test - 95

test distribution:
label
benign       51
malignant    29
normal       15
Name: count, dtype: int64

 Zero-Shot Evaluation using OpenAI CLIP ViT-B/16

In [ ]:
# Load OpenAI CLIP ViT-B/16.
openai_model, openai_preprocess, openai_tokenizer = load_openai_clip(device=device)

# Create evaluator.
openai_evaluator = ZeroShotEvaluator(openai_model, openai_preprocess, openai_tokenizer, PROMPT_REGISTRY, class_names_for_prompts, device=device)

# Build text embeddings.
openai_evaluator.build_text_embeddings()

# Evaluate on test set.
openai_metrics, _, _ = openai_evaluator.evaluate(test_df, batch_size=32, description='encoding test images (OpenAI CLIP)')

# Print results.
openai_evaluator.print_results(openai_metrics, 'OpenAI CLIP ViT-B/16')

# Save results.
results_path = project_root / 'results' / 'zero_shot_results.csv'
results_path.parent.mkdir(exist_ok=True)
save_results_to_csv(openai_metrics, results_path, 'openai_clip_vit_b16', append=False)
print(f'\nresults saved to - {results_path}')

benign tumor - torch.Size([8, 512])
malignant tumor - torch.Size([8, 512])
normal scan - torch.Size([8, 512])

encoding test images (OpenAI CLIP): 100%|██████████| 3/3 [00:01<00:00,  1.88it/s]

Zero-Shot Results: OpenAI CLIP ViT-B/16
accuracy - 0.5895
balanced Accuracy - 0.4585
macro F1 - 0.4589
AUC - 0.7102

per-class F1 -
  benign: 0.7132
  malignant: 0.3158
  normal: 0.3478

results saved to - c:\Users\mason\Desktop\busi-vlm-project\results\zero_shot_results.csv

Zero-Shot Evaluation using BiomedCLIP ViT-B/16

In [ ]:
# Load BiomedCLIP ViT-B/16.
biomedclip_model, _, biomedclip_preprocess, biomedclip_tokenizer = load_biomedclip(device=device)

# Create evaluator.
biomedclip_evaluator = ZeroShotEvaluator(biomedclip_model, biomedclip_preprocess, biomedclip_tokenizer, PROMPT_REGISTRY, class_names_for_prompts, device=device)

# Build text embeddings.
biomedclip_evaluator.build_text_embeddings()

# Evaluate on test set.
biomedclip_metrics, _, _ = biomedclip_evaluator.evaluate(test_df, batch_size=32, description='encoding test images (BiomedCLIP)')

# Print results.
biomedclip_evaluator.print_results(biomedclip_metrics, 'BiomedCLIP ViT-B/16')

# Save results.
save_results_to_csv(biomedclip_metrics, results_path, 'biomedclip_vit_b16', append=True)

print(f'\nresults saved to - {results_path}')

benign tumor - torch.Size([8, 512])
malignant tumor - torch.Size([8, 512])
normal scan - torch.Size([8, 512])

encoding test images (BiomedCLIP): 100%|██████████| 3/3 [00:01<00:00,  2.29it/s]

Zero-Shot Results: BiomedCLIP ViT-B/16
accuracy - 0.4105
balanced Accuracy - 0.4771
macro F1 - 0.3786
AUC - 0.7465

per-class F1 -
  benign: 0.1786
  malignant: 0.5225
  normal: 0.4348

results saved to - c:\Users\mason\Desktop\busi-vlm-project\results\zero_shot_results.csv

Zero-Shot Evaluation using UniMed-CLIP ViT-B/16

In [ ]:
# Load UniMed-CLIP ViT-B/16.
unimedclip_model, unimedclip_preprocess, unimedclip_tokenizer = load_unimedclip(device=device, project_root=project_root)

# Create evaluator.
unimedclip_evaluator = ZeroShotEvaluator(unimedclip_model, unimedclip_preprocess, unimedclip_tokenizer, PROMPT_REGISTRY, class_names_for_prompts, device=device)

# Build text embeddings.
unimedclip_evaluator.build_text_embeddings()

# Evaluate on test set.
unimedclip_metrics, _, _ = unimedclip_evaluator.evaluate(test_df, batch_size=32, description='encoding test images (UniMed-CLIP)')

# Print results.
unimedclip_evaluator.print_results(unimedclip_metrics, 'UniMed-CLIP ViT-B/16')

# Save results.
save_results_to_csv(unimedclip_metrics, results_path, 'unimedclip', append=True)
print(f'\nresults saved to - {results_path}')

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 106041.82it/s]
[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

benign tumor - torch.Size([8, 512])
malignant tumor - torch.Size([8, 512])
normal scan - torch.Size([8, 512])

encoding test images (UniMed-CLIP): 100%|██████████| 3/3 [00:01<00:00,  2.22it/s]

Zero-Shot Results: UniMed-CLIP ViT-B/16
accuracy - 0.3053
balanced Accuracy - 0.3968
macro F1 - 0.3042
AUC - 0.5876

per-class F1 -
  benign: 0.3235
  malignant: 0.2917
  normal: 0.2973

results saved to - c:\Users\mason\Desktop\busi-vlm-project\results\zero_shot_results.csv

Compare Zero-Shot Results

In [9]:
# Display zero-shot comparison.
zero_shot_results = pd.read_csv(results_path)
display(zero_shot_results)

,model,accuracy,balanced_accuracy,macro_f1,weighted_f1,auc,benign_precision,benign_recall,benign_f1,malignant_precision,malignant_recall,malignant_f1,normal_precision,normal_recall,normal_f1
0,openai_clip_vit_b16,0.589474,0.458508,0.458931,0.534183,0.710239,0.589744,0.901961,0.713178,0.666667,0.206897,0.315789,0.500000,0.266667,0.347826
1,biomedclip_vit_b16,0.410526,0.477124,0.378626,0.324021,0.746545,1.000000,0.098039,0.178571,0.353659,1.000000,0.522523,0.625000,0.333333,0.434783
2,unimedclip,0.305263,0.396800,0.304164,0.309661,0.587574,0.647059,0.215686,0.323529,0.368421,0.241379,0.291667,0.186441,0.733333,0.297297

Extract Frozen Image Features for Linear Probing

In [10]:
feature_batch_size = 32

model_specs = [
    {
        'model_name': 'openai_clip_vit_b16',
        'model': openai_model,
        'preprocess': openai_preprocess,
    },
    {
        'model_name': 'biomedclip_vit_b16',
        'model': biomedclip_model,
        'preprocess': biomedclip_preprocess,
    },
    {
        'model_name': 'unimedclip',
        'model': unimedclip_model,
        'preprocess': unimedclip_preprocess,
    },
]

feature_sets = {}

for spec in model_specs:
    model_name = spec['model_name']
    model = spec['model']
    preprocess = spec['preprocess']

    print(f'encoding frozen features - {model_name}')

    model.eval()

    feature_sets[model_name] = {
        'train': encode_images_batch(
            model,
            preprocess,
            train_df,
            device=device,
            batch_size=feature_batch_size,
            description=f'{model_name} train',
        ),
        'val': encode_images_batch(
            model,
            preprocess,
            val_df,
            device=device,
            batch_size=feature_batch_size,
            description=f'{model_name} val',
        ),
        'test': encode_images_batch(
            model,
            preprocess,
            test_df,
            device=device,
            batch_size=feature_batch_size,
            description=f'{model_name} test',
        ),
    }

    print(
        f"{model_name} features - "
        f"train {feature_sets[model_name]['train'].shape}, "
        f"val {feature_sets[model_name]['val'].shape}, "
        f"test {feature_sets[model_name]['test'].shape}"
    )

train_labels = train_df['label_index'].values
val_labels = val_df['label_index'].values
test_labels = test_df['label_index'].values

encoding frozen features - openai_clip_vit_b16

openai_clip_vit_b16 train: 100%|██████████| 14/14 [00:06<00:00,  2.18it/s]
openai_clip_vit_b16 val: 100%|██████████| 3/3 [00:01<00:00,  2.18it/s]
openai_clip_vit_b16 test: 100%|██████████| 3/3 [00:01<00:00,  2.24it/s]

openai_clip_vit_b16 features - train torch.Size([437, 512]), val torch.Size([93, 512]), test torch.Size([95, 512])
encoding frozen features - biomedclip_vit_b16

biomedclip_vit_b16 train: 100%|██████████| 14/14 [00:05<00:00,  2.36it/s]
biomedclip_vit_b16 val: 100%|██████████| 3/3 [00:01<00:00,  2.38it/s]
biomedclip_vit_b16 test: 100%|██████████| 3/3 [00:01<00:00,  2.37it/s]

biomedclip_vit_b16 features - train torch.Size([437, 512]), val torch.Size([93, 512]), test torch.Size([95, 512])
encoding frozen features - unimedclip

unimedclip train: 100%|██████████| 14/14 [00:06<00:00,  2.27it/s]
unimedclip val: 100%|██████████| 3/3 [00:01<00:00,  2.20it/s]
unimedclip test: 100%|██████████| 3/3 [00:01<00:00,  2.28it/s]

unimedclip features - train torch.Size([437, 512]), val torch.Size([93, 512]), test torch.Size([95, 512])

Set Up Shared Few-Shot Support Sets

In [11]:
# Few-shot setup.
shots_per_class = [1, 2, 4, 8, 16, 32]
seeds = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

train_labels = train_df['label_index'].values
val_labels = val_df['label_index'].values
test_labels = test_df['label_index'].values

shared_support_indices = make_kshot_indices(
    train_df,
    label_col='label_index',
    shots_per_class=shots_per_class,
    seeds=seeds,
)

Few-Shot Linear Probe Baseline

In [12]:
# Few-shot linear probe. The encoder is frozen and the linear classifier is trained on pre-extracted image features.
# We use a wider C search list from 0.000001 to 1000000.0 to tune the LogisticRegression regularisation strength for each few-shot setting.
probe_config = LinearProbeConfig(
    max_iter = 5000, 
    class_weight = 'balanced', 
    c_values = (0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1, 1.0, 10.0, 100.0, 1000.0, 10000.0, 100000.0, 1000000.0), 
    selection_metric = 'macro_f1'
)

all_results = []
all_aggregates = []

for spec in model_specs:
    model_name = spec['model_name']
    features = feature_sets[model_name]

    print(f'few-shot linear probe - {model_name}')

    results_df, aggregate_df = run_linear_probe_experiments(
        model_name=model_name,
        train_features=features["train"],
        train_labels=train_labels,
        val_features=features["val"],
        val_labels=val_labels,
        test_features=features["test"],
        test_labels=test_labels,
        class_names=busi_classes,
        ratios=shots_per_class,
        seeds=seeds,
        device=device,
        config=probe_config,
        verbose=False,
        kshot_indices=shared_support_indices
    )

    all_results.append(results_df)
    all_aggregates.append(aggregate_df)

fewshot_results = pd.concat(all_results, ignore_index=True)
fewshot_aggregate = pd.concat(all_aggregates, ignore_index=True)

summary_columns = [
    'model',
    'shots_per_class',
    'n_train_samples_mean',
    'accuracy_mean',
    'accuracy_std',
    'balanced_accuracy_mean',
    'balanced_accuracy_std',
    'macro_f1_mean',
    'macro_f1_std',
    'auc_mean',
    'auc_std'
]

display(fewshot_aggregate[summary_columns])

fewshot_dir = project_root / 'results' / 'fewshot_linear_probe'
fewshot_dir.mkdir(parents=True, exist_ok=True)

fewshot_results_path = fewshot_dir / 'fewshot_linear_probe_all_runs.csv'
fewshot_aggregate_path = fewshot_dir / 'fewshot_linear_probe_aggregate.csv'

fewshot_results.to_csv(fewshot_results_path, index=False)
fewshot_aggregate.to_csv(fewshot_aggregate_path, index=False)

print(f'few-shot runs saved to - {fewshot_results_path}')
print(f'few-shot aggregate saved to - {fewshot_aggregate_path}')

few-shot linear probe - openai_clip_vit_b16
model=openai_clip_vit_b16 shots=1 seed=1 | n=3 | c=1000.0 | val_f1=0.3106 | test_acc=0.2842 | test_f1=0.2671 | test_auc=0.6262
model=openai_clip_vit_b16 shots=1 seed=2 | n=3 | c=0.1 | val_f1=0.3912 | test_acc=0.4632 | test_f1=0.3942 | test_auc=0.5202
model=openai_clip_vit_b16 shots=1 seed=3 | n=3 | c=10.0 | val_f1=0.3077 | test_acc=0.2316 | test_f1=0.2284 | test_auc=0.6065
model=openai_clip_vit_b16 shots=1 seed=4 | n=3 | c=1.0 | val_f1=0.3474 | test_acc=0.4842 | test_f1=0.2757 | test_auc=0.5258
model=openai_clip_vit_b16 shots=1 seed=5 | n=3 | c=1000.0 | val_f1=0.3395 | test_acc=0.5263 | test_f1=0.4613 | test_auc=0.5714
model=openai_clip_vit_b16 shots=1 seed=6 | n=3 | c=1.0 | val_f1=0.3955 | test_acc=0.4947 | test_f1=0.4332 | test_auc=0.6205
model=openai_clip_vit_b16 shots=1 seed=7 | n=3 | c=0.1 | val_f1=0.4570 | test_acc=0.4842 | test_f1=0.4890 | test_auc=0.7358
model=openai_clip_vit_b16 shots=1 seed=8 | n=3 | c=0.1 | val_f1=0.4131 | test_acc=0.4421 | test_f1=0.3729 | test_auc=0.5598
model=openai_clip_vit_b16 shots=1 seed=9 | n=3 | c=1e-06 | val_f1=0.3918 | test_acc=0.4105 | test_f1=0.4220 | test_auc=0.6050
model=openai_clip_vit_b16 shots=1 seed=10 | n=3 | c=0.1 | val_f1=0.1902 | test_acc=0.3579 | test_f1=0.2923 | test_auc=0.5532
model=openai_clip_vit_b16 shots=2 seed=1 | n=6 | c=10000.0 | val_f1=0.5167 | test_acc=0.3684 | test_f1=0.3194 | test_auc=0.5948
model=openai_clip_vit_b16 shots=2 seed=2 | n=6 | c=1000000.0 | val_f1=0.3235 | test_acc=0.2842 | test_f1=0.2482 | test_auc=0.4623
model=openai_clip_vit_b16 shots=2 seed=3 | n=6 | c=1e-06 | val_f1=0.2599 | test_acc=0.4105 | test_f1=0.3806 | test_auc=0.5496
model=openai_clip_vit_b16 shots=2 seed=4 | n=6 | c=10000.0 | val_f1=0.4216 | test_acc=0.4211 | test_f1=0.3297 | test_auc=0.5640
model=openai_clip_vit_b16 shots=2 seed=5 | n=6 | c=1.0 | val_f1=0.4467 | test_acc=0.2947 | test_f1=0.2971 | test_auc=0.5664
model=openai_clip_vit_b16 shots=2 seed=6 | n=6 | c=100000.0 | val_f1=0.4793 | test_acc=0.3579 | test_f1=0.3111 | test_auc=0.6104
model=openai_clip_vit_b16 shots=2 seed=7 | n=6 | c=100000.0 | val_f1=0.3665 | test_acc=0.5053 | test_f1=0.3957 | test_auc=0.6236
model=openai_clip_vit_b16 shots=2 seed=8 | n=6 | c=100000.0 | val_f1=0.5424 | test_acc=0.4526 | test_f1=0.3955 | test_auc=0.5976
model=openai_clip_vit_b16 shots=2 seed=9 | n=6 | c=0.1 | val_f1=0.3976 | test_acc=0.4632 | test_f1=0.4597 | test_auc=0.6505
model=openai_clip_vit_b16 shots=2 seed=10 | n=6 | c=10.0 | val_f1=0.4464 | test_acc=0.4105 | test_f1=0.3991 | test_auc=0.6727
model=openai_clip_vit_b16 shots=4 seed=1 | n=12 | c=10.0 | val_f1=0.6465 | test_acc=0.5579 | test_f1=0.5205 | test_auc=0.6947
model=openai_clip_vit_b16 shots=4 seed=2 | n=12 | c=100000.0 | val_f1=0.5585 | test_acc=0.3263 | test_f1=0.3265 | test_auc=0.5926
model=openai_clip_vit_b16 shots=4 seed=3 | n=12 | c=1000.0 | val_f1=0.6144 | test_acc=0.4947 | test_f1=0.4854 | test_auc=0.6925
model=openai_clip_vit_b16 shots=4 seed=4 | n=12 | c=0.1 | val_f1=0.5841 | test_acc=0.5895 | test_f1=0.5677 | test_auc=0.7493
model=openai_clip_vit_b16 shots=4 seed=5 | n=12 | c=1000000.0 | val_f1=0.5911 | test_acc=0.4842 | test_f1=0.3828 | test_auc=0.6524
model=openai_clip_vit_b16 shots=4 seed=6 | n=12 | c=100.0 | val_f1=0.4917 | test_acc=0.4105 | test_f1=0.4178 | test_auc=0.6523
model=openai_clip_vit_b16 shots=4 seed=7 | n=12 | c=1000.0 | val_f1=0.5722 | test_acc=0.4632 | test_f1=0.4590 | test_auc=0.7206
model=openai_clip_vit_b16 shots=4 seed=8 | n=12 | c=100000.0 | val_f1=0.7119 | test_acc=0.6316 | test_f1=0.6151 | test_auc=0.8167
model=openai_clip_vit_b16 shots=4 seed=9 | n=12 | c=0.1 | val_f1=0.5809 | test_acc=0.6421 | test_f1=0.6024 | test_auc=0.7558
model=openai_clip_vit_b16 shots=4 seed=10 | n=12 | c=10000.0 | val_f1=0.5611 | test_acc=0.4947 | test_f1=0.4864 | test_auc=0.7207
model=openai_clip_vit_b16 shots=8 seed=1 | n=24 | c=10.0 | val_f1=0.5615 | test_acc=0.5368 | test_f1=0.5200 | test_auc=0.7282
model=openai_clip_vit_b16 shots=8 seed=2 | n=24 | c=1000.0 | val_f1=0.6356 | test_acc=0.4737 | test_f1=0.4751 | test_auc=0.7769
model=openai_clip_vit_b16 shots=8 seed=3 | n=24 | c=100.0 | val_f1=0.4969 | test_acc=0.4632 | test_f1=0.4532 | test_auc=0.7582
model=openai_clip_vit_b16 shots=8 seed=4 | n=24 | c=1000.0 | val_f1=0.6406 | test_acc=0.5895 | test_f1=0.5811 | test_auc=0.7868
model=openai_clip_vit_b16 shots=8 seed=5 | n=24 | c=1.0 | val_f1=0.5937 | test_acc=0.4421 | test_f1=0.4186 | test_auc=0.6194
model=openai_clip_vit_b16 shots=8 seed=6 | n=24 | c=1e-06 | val_f1=0.5449 | test_acc=0.4000 | test_f1=0.3992 | test_auc=0.6318
model=openai_clip_vit_b16 shots=8 seed=7 | n=24 | c=1000.0 | val_f1=0.5014 | test_acc=0.6737 | test_f1=0.6386 | test_auc=0.8238
model=openai_clip_vit_b16 shots=8 seed=8 | n=24 | c=10.0 | val_f1=0.5997 | test_acc=0.4526 | test_f1=0.4161 | test_auc=0.6919
model=openai_clip_vit_b16 shots=8 seed=9 | n=24 | c=100000.0 | val_f1=0.5886 | test_acc=0.5368 | test_f1=0.5294 | test_auc=0.7390
model=openai_clip_vit_b16 shots=8 seed=10 | n=24 | c=1000.0 | val_f1=0.6403 | test_acc=0.4947 | test_f1=0.4817 | test_auc=0.7037
model=openai_clip_vit_b16 shots=16 seed=1 | n=48 | c=1000.0 | val_f1=0.6349 | test_acc=0.5895 | test_f1=0.5733 | test_auc=0.8039
model=openai_clip_vit_b16 shots=16 seed=2 | n=48 | c=100.0 | val_f1=0.6543 | test_acc=0.5474 | test_f1=0.5316 | test_auc=0.7489
model=openai_clip_vit_b16 shots=16 seed=3 | n=48 | c=100.0 | val_f1=0.6497 | test_acc=0.6000 | test_f1=0.5997 | test_auc=0.8119
model=openai_clip_vit_b16 shots=16 seed=4 | n=48 | c=100.0 | val_f1=0.5614 | test_acc=0.5158 | test_f1=0.4936 | test_auc=0.7614
model=openai_clip_vit_b16 shots=16 seed=5 | n=48 | c=100.0 | val_f1=0.6078 | test_acc=0.4842 | test_f1=0.4803 | test_auc=0.7437
model=openai_clip_vit_b16 shots=16 seed=6 | n=48 | c=10.0 | val_f1=0.6810 | test_acc=0.6211 | test_f1=0.6093 | test_auc=0.7962
model=openai_clip_vit_b16 shots=16 seed=7 | n=48 | c=100.0 | val_f1=0.7176 | test_acc=0.6421 | test_f1=0.6222 | test_auc=0.8334
model=openai_clip_vit_b16 shots=16 seed=8 | n=48 | c=100.0 | val_f1=0.6184 | test_acc=0.5789 | test_f1=0.5715 | test_auc=0.7825
model=openai_clip_vit_b16 shots=16 seed=9 | n=48 | c=10000.0 | val_f1=0.7023 | test_acc=0.6105 | test_f1=0.6092 | test_auc=0.8329
model=openai_clip_vit_b16 shots=16 seed=10 | n=48 | c=1000000.0 | val_f1=0.5969 | test_acc=0.6105 | test_f1=0.5840 | test_auc=0.8062
model=openai_clip_vit_b16 shots=32 seed=1 | n=96 | c=100.0 | val_f1=0.6614 | test_acc=0.6947 | test_f1=0.6840 | test_auc=0.8490
model=openai_clip_vit_b16 shots=32 seed=2 | n=96 | c=10.0 | val_f1=0.7391 | test_acc=0.6632 | test_f1=0.6394 | test_auc=0.8150
model=openai_clip_vit_b16 shots=32 seed=3 | n=96 | c=100000.0 | val_f1=0.6748 | test_acc=0.5895 | test_f1=0.5816 | test_auc=0.8214
model=openai_clip_vit_b16 shots=32 seed=4 | n=96 | c=100000.0 | val_f1=0.6083 | test_acc=0.6316 | test_f1=0.6101 | test_auc=0.8180
model=openai_clip_vit_b16 shots=32 seed=5 | n=96 | c=10.0 | val_f1=0.7280 | test_acc=0.5895 | test_f1=0.5838 | test_auc=0.8174
model=openai_clip_vit_b16 shots=32 seed=6 | n=96 | c=1.0 | val_f1=0.6881 | test_acc=0.5474 | test_f1=0.5423 | test_auc=0.7386
model=openai_clip_vit_b16 shots=32 seed=7 | n=96 | c=100.0 | val_f1=0.7304 | test_acc=0.5895 | test_f1=0.5733 | test_auc=0.8282
model=openai_clip_vit_b16 shots=32 seed=8 | n=96 | c=1000000.0 | val_f1=0.6628 | test_acc=0.6632 | test_f1=0.6500 | test_auc=0.8327
model=openai_clip_vit_b16 shots=32 seed=9 | n=96 | c=100.0 | val_f1=0.6556 | test_acc=0.6947 | test_f1=0.6839 | test_auc=0.8730
model=openai_clip_vit_b16 shots=32 seed=10 | n=96 | c=100.0 | val_f1=0.6037 | test_acc=0.6105 | test_f1=0.5917 | test_auc=0.8056
few-shot linear probe - biomedclip_vit_b16
model=biomedclip_vit_b16 shots=1 seed=1 | n=3 | c=100000.0 | val_f1=0.4020 | test_acc=0.5368 | test_f1=0.4120 | test_auc=0.5991
model=biomedclip_vit_b16 shots=1 seed=2 | n=3 | c=1e-06 | val_f1=0.2865 | test_acc=0.3474 | test_f1=0.2462 | test_auc=0.4812
model=biomedclip_vit_b16 shots=1 seed=3 | n=3 | c=10.0 | val_f1=0.3831 | test_acc=0.4947 | test_f1=0.4457 | test_auc=0.6190
model=biomedclip_vit_b16 shots=1 seed=4 | n=3 | c=1000000.0 | val_f1=0.4509 | test_acc=0.4737 | test_f1=0.4453 | test_auc=0.6707
model=biomedclip_vit_b16 shots=1 seed=5 | n=3 | c=0.1 | val_f1=0.5451 | test_acc=0.5789 | test_f1=0.5603 | test_auc=0.7249
model=biomedclip_vit_b16 shots=1 seed=6 | n=3 | c=1.0 | val_f1=0.4280 | test_acc=0.4632 | test_f1=0.4296 | test_auc=0.8360
model=biomedclip_vit_b16 shots=1 seed=7 | n=3 | c=0.1 | val_f1=0.4024 | test_acc=0.4105 | test_f1=0.3899 | test_auc=0.7721
model=biomedclip_vit_b16 shots=1 seed=8 | n=3 | c=0.1 | val_f1=0.3894 | test_acc=0.4211 | test_f1=0.3348 | test_auc=0.5938
model=biomedclip_vit_b16 shots=1 seed=9 | n=3 | c=1.0 | val_f1=0.2756 | test_acc=0.2526 | test_f1=0.3050 | test_auc=0.5539
model=biomedclip_vit_b16 shots=1 seed=10 | n=3 | c=100.0 | val_f1=0.4105 | test_acc=0.4000 | test_f1=0.3969 | test_auc=0.7867
model=biomedclip_vit_b16 shots=2 seed=1 | n=6 | c=10.0 | val_f1=0.6803 | test_acc=0.6000 | test_f1=0.5907 | test_auc=0.7944
model=biomedclip_vit_b16 shots=2 seed=2 | n=6 | c=100000.0 | val_f1=0.5206 | test_acc=0.4947 | test_f1=0.4971 | test_auc=0.7258
model=biomedclip_vit_b16 shots=2 seed=3 | n=6 | c=10000.0 | val_f1=0.3321 | test_acc=0.3474 | test_f1=0.3145 | test_auc=0.4998
model=biomedclip_vit_b16 shots=2 seed=4 | n=6 | c=0.1 | val_f1=0.6295 | test_acc=0.6737 | test_f1=0.6777 | test_auc=0.8142
model=biomedclip_vit_b16 shots=2 seed=5 | n=6 | c=100.0 | val_f1=0.3788 | test_acc=0.2737 | test_f1=0.2731 | test_auc=0.5943
model=biomedclip_vit_b16 shots=2 seed=6 | n=6 | c=100000.0 | val_f1=0.7174 | test_acc=0.7263 | test_f1=0.7250 | test_auc=0.8368
model=biomedclip_vit_b16 shots=2 seed=7 | n=6 | c=10000.0 | val_f1=0.5010 | test_acc=0.6000 | test_f1=0.5451 | test_auc=0.7519
model=biomedclip_vit_b16 shots=2 seed=8 | n=6 | c=10.0 | val_f1=0.6212 | test_acc=0.6000 | test_f1=0.5707 | test_auc=0.8525
model=biomedclip_vit_b16 shots=2 seed=9 | n=6 | c=10.0 | val_f1=0.4739 | test_acc=0.5158 | test_f1=0.5141 | test_auc=0.7299
model=biomedclip_vit_b16 shots=2 seed=10 | n=6 | c=10.0 | val_f1=0.4492 | test_acc=0.4421 | test_f1=0.4403 | test_auc=0.7529
model=biomedclip_vit_b16 shots=4 seed=1 | n=12 | c=10.0 | val_f1=0.6552 | test_acc=0.6526 | test_f1=0.6448 | test_auc=0.8123
model=biomedclip_vit_b16 shots=4 seed=2 | n=12 | c=100000.0 | val_f1=0.7132 | test_acc=0.6947 | test_f1=0.6659 | test_auc=0.8197
model=biomedclip_vit_b16 shots=4 seed=3 | n=12 | c=0.01 | val_f1=0.7472 | test_acc=0.6737 | test_f1=0.6357 | test_auc=0.8239
model=biomedclip_vit_b16 shots=4 seed=4 | n=12 | c=100.0 | val_f1=0.7280 | test_acc=0.7053 | test_f1=0.6834 | test_auc=0.8658
model=biomedclip_vit_b16 shots=4 seed=5 | n=12 | c=10.0 | val_f1=0.6611 | test_acc=0.5895 | test_f1=0.5751 | test_auc=0.7720
model=biomedclip_vit_b16 shots=4 seed=6 | n=12 | c=1000.0 | val_f1=0.6594 | test_acc=0.5789 | test_f1=0.5966 | test_auc=0.8067
model=biomedclip_vit_b16 shots=4 seed=7 | n=12 | c=100.0 | val_f1=0.7108 | test_acc=0.6316 | test_f1=0.6364 | test_auc=0.8027
model=biomedclip_vit_b16 shots=4 seed=8 | n=12 | c=0.1 | val_f1=0.6298 | test_acc=0.6632 | test_f1=0.6548 | test_auc=0.8509
model=biomedclip_vit_b16 shots=4 seed=9 | n=12 | c=10.0 | val_f1=0.6095 | test_acc=0.6000 | test_f1=0.5583 | test_auc=0.7873
model=biomedclip_vit_b16 shots=4 seed=10 | n=12 | c=10.0 | val_f1=0.6642 | test_acc=0.6632 | test_f1=0.6370 | test_auc=0.8408
model=biomedclip_vit_b16 shots=8 seed=1 | n=24 | c=0.1 | val_f1=0.5994 | test_acc=0.6526 | test_f1=0.6406 | test_auc=0.8088
model=biomedclip_vit_b16 shots=8 seed=2 | n=24 | c=1.0 | val_f1=0.6936 | test_acc=0.6947 | test_f1=0.6774 | test_auc=0.8314
model=biomedclip_vit_b16 shots=8 seed=3 | n=24 | c=1000.0 | val_f1=0.6924 | test_acc=0.6105 | test_f1=0.6025 | test_auc=0.8629
model=biomedclip_vit_b16 shots=8 seed=4 | n=24 | c=1000000.0 | val_f1=0.7065 | test_acc=0.7158 | test_f1=0.6921 | test_auc=0.8461
model=biomedclip_vit_b16 shots=8 seed=5 | n=24 | c=1000.0 | val_f1=0.7606 | test_acc=0.6842 | test_f1=0.6480 | test_auc=0.8261
model=biomedclip_vit_b16 shots=8 seed=6 | n=24 | c=100000.0 | val_f1=0.6910 | test_acc=0.6000 | test_f1=0.5918 | test_auc=0.7945
model=biomedclip_vit_b16 shots=8 seed=7 | n=24 | c=10.0 | val_f1=0.6825 | test_acc=0.6842 | test_f1=0.6935 | test_auc=0.8460
model=biomedclip_vit_b16 shots=8 seed=8 | n=24 | c=10.0 | val_f1=0.6964 | test_acc=0.6000 | test_f1=0.6100 | test_auc=0.8073
model=biomedclip_vit_b16 shots=8 seed=9 | n=24 | c=0.01 | val_f1=0.6880 | test_acc=0.6947 | test_f1=0.6952 | test_auc=0.8351
model=biomedclip_vit_b16 shots=8 seed=10 | n=24 | c=10.0 | val_f1=0.6068 | test_acc=0.6316 | test_f1=0.6279 | test_auc=0.7976
model=biomedclip_vit_b16 shots=16 seed=1 | n=48 | c=100.0 | val_f1=0.7178 | test_acc=0.6842 | test_f1=0.6533 | test_auc=0.8726
model=biomedclip_vit_b16 shots=16 seed=2 | n=48 | c=1.0 | val_f1=0.7497 | test_acc=0.5789 | test_f1=0.5755 | test_auc=0.7879
model=biomedclip_vit_b16 shots=16 seed=3 | n=48 | c=10.0 | val_f1=0.7717 | test_acc=0.6737 | test_f1=0.6726 | test_auc=0.8914
model=biomedclip_vit_b16 shots=16 seed=4 | n=48 | c=1.0 | val_f1=0.7914 | test_acc=0.7053 | test_f1=0.6856 | test_auc=0.8694
model=biomedclip_vit_b16 shots=16 seed=5 | n=48 | c=1000000.0 | val_f1=0.7387 | test_acc=0.6842 | test_f1=0.6714 | test_auc=0.8509
model=biomedclip_vit_b16 shots=16 seed=6 | n=48 | c=1.0 | val_f1=0.6986 | test_acc=0.7263 | test_f1=0.7162 | test_auc=0.8781
model=biomedclip_vit_b16 shots=16 seed=7 | n=48 | c=10000.0 | val_f1=0.7213 | test_acc=0.7895 | test_f1=0.7786 | test_auc=0.9141
model=biomedclip_vit_b16 shots=16 seed=8 | n=48 | c=10.0 | val_f1=0.7262 | test_acc=0.6316 | test_f1=0.6078 | test_auc=0.8348
model=biomedclip_vit_b16 shots=16 seed=9 | n=48 | c=1000.0 | val_f1=0.7531 | test_acc=0.7579 | test_f1=0.7445 | test_auc=0.8976
model=biomedclip_vit_b16 shots=16 seed=10 | n=48 | c=1.0 | val_f1=0.7581 | test_acc=0.7895 | test_f1=0.7769 | test_auc=0.8758
model=biomedclip_vit_b16 shots=32 seed=1 | n=96 | c=10.0 | val_f1=0.7443 | test_acc=0.7263 | test_f1=0.7210 | test_auc=0.8772
model=biomedclip_vit_b16 shots=32 seed=2 | n=96 | c=10.0 | val_f1=0.7592 | test_acc=0.6632 | test_f1=0.6702 | test_auc=0.8626
model=biomedclip_vit_b16 shots=32 seed=3 | n=96 | c=10.0 | val_f1=0.7146 | test_acc=0.7158 | test_f1=0.7113 | test_auc=0.8743
model=biomedclip_vit_b16 shots=32 seed=4 | n=96 | c=100.0 | val_f1=0.7418 | test_acc=0.6842 | test_f1=0.6932 | test_auc=0.8548
model=biomedclip_vit_b16 shots=32 seed=5 | n=96 | c=10.0 | val_f1=0.7862 | test_acc=0.7368 | test_f1=0.7352 | test_auc=0.8922
model=biomedclip_vit_b16 shots=32 seed=6 | n=96 | c=100.0 | val_f1=0.7661 | test_acc=0.7053 | test_f1=0.6933 | test_auc=0.8882
model=biomedclip_vit_b16 shots=32 seed=7 | n=96 | c=10.0 | val_f1=0.7813 | test_acc=0.7368 | test_f1=0.7341 | test_auc=0.9046
model=biomedclip_vit_b16 shots=32 seed=8 | n=96 | c=1.0 | val_f1=0.7462 | test_acc=0.7263 | test_f1=0.7156 | test_auc=0.8705
model=biomedclip_vit_b16 shots=32 seed=9 | n=96 | c=1.0 | val_f1=0.7129 | test_acc=0.6632 | test_f1=0.6665 | test_auc=0.8410
model=biomedclip_vit_b16 shots=32 seed=10 | n=96 | c=10.0 | val_f1=0.7531 | test_acc=0.7158 | test_f1=0.7118 | test_auc=0.8996
few-shot linear probe - unimedclip
model=unimedclip shots=1 seed=1 | n=3 | c=10.0 | val_f1=0.4165 | test_acc=0.3053 | test_f1=0.3017 | test_auc=0.4977
model=unimedclip shots=1 seed=2 | n=3 | c=1000000.0 | val_f1=0.2964 | test_acc=0.5263 | test_f1=0.3954 | test_auc=0.5970
model=unimedclip shots=1 seed=3 | n=3 | c=1000000.0 | val_f1=0.2996 | test_acc=0.4000 | test_f1=0.3533 | test_auc=0.5453
model=unimedclip shots=1 seed=4 | n=3 | c=1e-06 | val_f1=0.3959 | test_acc=0.2947 | test_f1=0.2849 | test_auc=0.5413
model=unimedclip shots=1 seed=5 | n=3 | c=0.1 | val_f1=0.4256 | test_acc=0.3789 | test_f1=0.3337 | test_auc=0.5430
model=unimedclip shots=1 seed=6 | n=3 | c=1.0 | val_f1=0.4997 | test_acc=0.4632 | test_f1=0.4452 | test_auc=0.5341
model=unimedclip shots=1 seed=7 | n=3 | c=10.0 | val_f1=0.4016 | test_acc=0.3579 | test_f1=0.3539 | test_auc=0.5799
model=unimedclip shots=1 seed=8 | n=3 | c=1.0 | val_f1=0.3265 | test_acc=0.2526 | test_f1=0.2243 | test_auc=0.5037
model=unimedclip shots=1 seed=9 | n=3 | c=1e-06 | val_f1=0.4289 | test_acc=0.4105 | test_f1=0.4285 | test_auc=0.5395
model=unimedclip shots=1 seed=10 | n=3 | c=10000.0 | val_f1=0.2897 | test_acc=0.2947 | test_f1=0.2944 | test_auc=0.5730
model=unimedclip shots=2 seed=1 | n=6 | c=100000.0 | val_f1=0.4963 | test_acc=0.4526 | test_f1=0.4436 | test_auc=0.6391
model=unimedclip shots=2 seed=2 | n=6 | c=10000.0 | val_f1=0.5380 | test_acc=0.3684 | test_f1=0.3710 | test_auc=0.6098
model=unimedclip shots=2 seed=3 | n=6 | c=1000000.0 | val_f1=0.3215 | test_acc=0.3474 | test_f1=0.3350 | test_auc=0.5059
model=unimedclip shots=2 seed=4 | n=6 | c=100000.0 | val_f1=0.4972 | test_acc=0.3895 | test_f1=0.3690 | test_auc=0.5889
model=unimedclip shots=2 seed=5 | n=6 | c=100000.0 | val_f1=0.3739 | test_acc=0.4105 | test_f1=0.3850 | test_auc=0.4865
model=unimedclip shots=2 seed=6 | n=6 | c=100.0 | val_f1=0.4794 | test_acc=0.4737 | test_f1=0.4535 | test_auc=0.5665
model=unimedclip shots=2 seed=7 | n=6 | c=1000000.0 | val_f1=0.4703 | test_acc=0.4526 | test_f1=0.4236 | test_auc=0.6134
model=unimedclip shots=2 seed=8 | n=6 | c=1000.0 | val_f1=0.4047 | test_acc=0.5263 | test_f1=0.4743 | test_auc=0.6496
model=unimedclip shots=2 seed=9 | n=6 | c=100.0 | val_f1=0.4277 | test_acc=0.3263 | test_f1=0.3311 | test_auc=0.5709
model=unimedclip shots=2 seed=10 | n=6 | c=1.0 | val_f1=0.4873 | test_acc=0.4316 | test_f1=0.4316 | test_auc=0.7099
model=unimedclip shots=4 seed=1 | n=12 | c=10000.0 | val_f1=0.6221 | test_acc=0.5158 | test_f1=0.4867 | test_auc=0.7050
model=unimedclip shots=4 seed=2 | n=12 | c=100000.0 | val_f1=0.4822 | test_acc=0.3579 | test_f1=0.3442 | test_auc=0.5988
model=unimedclip shots=4 seed=3 | n=12 | c=1e-06 | val_f1=0.5900 | test_acc=0.4947 | test_f1=0.4502 | test_auc=0.6083
model=unimedclip shots=4 seed=4 | n=12 | c=1000.0 | val_f1=0.5135 | test_acc=0.5895 | test_f1=0.5733 | test_auc=0.7323
model=unimedclip shots=4 seed=5 | n=12 | c=100.0 | val_f1=0.4307 | test_acc=0.4316 | test_f1=0.4157 | test_auc=0.6160
model=unimedclip shots=4 seed=6 | n=12 | c=100000.0 | val_f1=0.4806 | test_acc=0.4526 | test_f1=0.4337 | test_auc=0.6595
model=unimedclip shots=4 seed=7 | n=12 | c=1000000.0 | val_f1=0.5463 | test_acc=0.5368 | test_f1=0.4971 | test_auc=0.7010
model=unimedclip shots=4 seed=8 | n=12 | c=1000.0 | val_f1=0.5417 | test_acc=0.4842 | test_f1=0.4710 | test_auc=0.6538
model=unimedclip shots=4 seed=9 | n=12 | c=100.0 | val_f1=0.5623 | test_acc=0.5263 | test_f1=0.4828 | test_auc=0.6501
model=unimedclip shots=4 seed=10 | n=12 | c=10000.0 | val_f1=0.5579 | test_acc=0.6105 | test_f1=0.5858 | test_auc=0.7363
model=unimedclip shots=8 seed=1 | n=24 | c=1000.0 | val_f1=0.5087 | test_acc=0.5474 | test_f1=0.5175 | test_auc=0.6309
model=unimedclip shots=8 seed=2 | n=24 | c=100.0 | val_f1=0.4926 | test_acc=0.5474 | test_f1=0.5224 | test_auc=0.7324
model=unimedclip shots=8 seed=3 | n=24 | c=100.0 | val_f1=0.5525 | test_acc=0.5368 | test_f1=0.5167 | test_auc=0.7090
model=unimedclip shots=8 seed=4 | n=24 | c=100000.0 | val_f1=0.6104 | test_acc=0.5474 | test_f1=0.5209 | test_auc=0.7330
model=unimedclip shots=8 seed=5 | n=24 | c=1000.0 | val_f1=0.6505 | test_acc=0.5158 | test_f1=0.4705 | test_auc=0.6748
model=unimedclip shots=8 seed=6 | n=24 | c=1000.0 | val_f1=0.4907 | test_acc=0.4526 | test_f1=0.4026 | test_auc=0.6389
model=unimedclip shots=8 seed=7 | n=24 | c=100000.0 | val_f1=0.5449 | test_acc=0.5789 | test_f1=0.5612 | test_auc=0.6666
model=unimedclip shots=8 seed=8 | n=24 | c=1000.0 | val_f1=0.4299 | test_acc=0.4421 | test_f1=0.4258 | test_auc=0.5951
model=unimedclip shots=8 seed=9 | n=24 | c=100000.0 | val_f1=0.5212 | test_acc=0.5684 | test_f1=0.5663 | test_auc=0.8050

,model,shots_per_class,n_train_samples_mean,accuracy_mean,accuracy_std,balanced_accuracy_mean,balanced_accuracy_std,macro_f1_mean,macro_f1_std,auc_mean,auc_std
0,openai_clip_vit_b16,1,3.0,0.417895,0.097371,0.425977,0.081931,0.363616,0.091253,0.592459,0.062857
1,openai_clip_vit_b16,2,6.0,0.396842,0.071229,0.414609,0.059215,0.353611,0.062737,0.589182,0.058942
2,openai_clip_vit_b16,4,12.0,0.509474,0.098771,0.532955,0.073937,0.486383,0.094018,0.704749,0.063212
3,openai_clip_vit_b16,8,24.0,0.506316,0.080388,0.554109,0.070501,0.491295,0.076941,0.725962,0.065789
4,openai_clip_vit_b16,16,48.0,0.580000,0.049733,0.621758,0.047743,0.567467,0.049637,0.792098,0.032243
5,openai_clip_vit_b16,32,96.0,0.627368,0.050164,0.663899,0.044015,0.614018,0.048308,0.819875,0.034551
6,biomedclip_vit_b16,1,3.0,0.437895,0.094176,0.455722,0.109757,0.396557,0.086791,0.663741,0.113909
7,biomedclip_vit_b16,2,6.0,0.527368,0.142220,0.573960,0.135318,0.514834,0.143334,0.735255,0.110464
8,biomedclip_vit_b16,4,12.0,0.645263,0.043839,0.669475,0.041019,0.628804,0.039956,0.818208,0.028601
9,biomedclip_vit_b16,8,24.0,0.656842,0.043599,0.692351,0.041935,0.647901,0.039785,0.825581,0.022897
10,biomedclip_vit_b16,16,48.0,0.702105,0.067136,0.722448,0.066660,0.688249,0.067432,0.867267,0.035824
11,biomedclip_vit_b16,32,96.0,0.707368,0.027982,0.751977,0.031305,0.705227,0.023982,0.876505,0.020196
12,unimedclip,1,3.0,0.368421,0.085083,0.379563,0.050984,0.341526,0.068586,0.545444,0.031296
13,unimedclip,2,6.0,0.417895,0.061589,0.444467,0.062079,0.401793,0.050339,0.594051,0.066504
14,unimedclip,4,12.0,0.500000,0.074474,0.500586,0.059119,0.474050,0.071158,0.666102,0.050412
15,unimedclip,8,24.0,0.536842,0.056359,0.534181,0.070044,0.507714,0.058016,0.695569,0.066026
16,unimedclip,16,48.0,0.616842,0.037856,0.627884,0.044904,0.593307,0.038129,0.779193,0.034761
17,unimedclip,32,96.0,0.654737,0.043768,0.681307,0.055416,0.640261,0.046805,0.821384,0.034868

few-shot runs saved to - c:\Users\mason\Desktop\busi-vlm-project\results\fewshot_linear_probe\fewshot_linear_probe_all_runs.csv
few-shot aggregate saved to - c:\Users\mason\Desktop\busi-vlm-project\results\fewshot_linear_probe\fewshot_linear_probe_aggregate.csv

Shared LoRA Setup

In [13]:
# Use BUSI class names here, not prompt-mapped zero-shot names.
lora_class_names = busi_classes

lora_base_save_dir = project_root/'results'/'few_shot_lora'
lora_base_save_dir.mkdir(parents=True, exist_ok=True)

Few-Shot LoRA Fine-Tuning using OpenAI CLIP ViT-B/16

In [14]:
# Run LoRA training for OpenAI CLIP.
args = get_args([])
args.console_log = False
args.show_progress = True
args.log_epochs = False
args.log_train_metrics = False

args.model_name = 'openai_clip_vit_b16'
args.device = device
args.num_classes = len(busi_classes)
args.encoder = 'vision'

# Training knobs.
args.epochs = 100
args.batch_size = 8
args.accumulation_steps = 4
args.patience = 18
args.grad_clip = 1.0

# Optimizer knobs.
args.lr = 1e-4
args.head_lr = 1e-3
args.lora_lr = 1e-4
args.lr_min = 1e-7
args.head_weight_decay = 1e-3
args.lora_weight_decay = 1e-5

# LoRA knobs.
args.lora_layers = None
args.lora_rank = 16
args.lora_alpha = 32
args.lora_dropout = 0.1

# Target q, k, v, and output projection for a fair comparison with BiomedCLIP qkv + proj.
args.clip_lora_targets = ['q', 'k', 'v', 'o']

# Use eval preprocessing during LoRA training for a controlled few-shot comparison.
args.use_eval_preprocess_for_train = False

save_dir = lora_base_save_dir / args.model_name

openai_lora_results_df, openai_lora_summary_df = run_kshot_experiments(
    args=args,
    train_df=train_df,
    val_df=val_df,
    test_df=test_df,
    class_names=lora_class_names,
    ks=shots_per_class,
    seeds=seeds,
    save_dir=save_dir,
    support_indices=shared_support_indices,
)

openai_lora_summary_df

LoRA few-shot: model=openai_clip | k=[1, 2, 4, 8, 16, 32] | seeds=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10] | rank=16 | alpha=32 | dropout=0.1 | layers=None
injected lora adapters to 12 layers (clip vision encoder)
trainable params: 1,179,648 / 150,800,385

LoRA model check: openai_clip
  trainable vision tensors: 96
  vision trainable params: 1,179,648 / 150,800,385
  classifier trainable params: 1,539
  total trainable params: 1,181,187

openai_clip k=1 seed=1:  23%|██▎       | 23/100 [00:40<02:17,  1.78s/it, best=0.4655, head_lr=8.6e-04, lora_lr=8.6e-05, loss=0.7079, val_f1=0.4088]

done model=openai_clip k=1 seed=1 best_epoch=6 best_val_f1=0.4655 test_acc=0.2526 test_f1=0.2627 test_auc=0.4823

openai_clip k=1 seed=2:  33%|███▎      | 33/100 [01:02<02:06,  1.89s/it, best=0.4514, head_lr=7.4e-04, lora_lr=7.4e-05, loss=0.5502, val_f1=0.4004]

done model=openai_clip k=1 seed=2 best_epoch=16 best_val_f1=0.4514 test_acc=0.4421 test_f1=0.4210 test_auc=0.5695

openai_clip k=1 seed=3:  36%|███▌      | 36/100 [01:07<01:59,  1.87s/it, best=0.2673, head_lr=7.0e-04, lora_lr=7.0e-05, loss=0.5276, val_f1=0.2478]

done model=openai_clip k=1 seed=3 best_epoch=19 best_val_f1=0.2673 test_acc=0.3474 test_f1=0.2913 test_auc=0.5899

openai_clip k=1 seed=4:  47%|████▋     | 47/100 [01:26<01:37,  1.83s/it, best=0.4151, head_lr=5.3e-04, lora_lr=5.3e-05, loss=0.4347, val_f1=0.3829]

done model=openai_clip k=1 seed=4 best_epoch=30 best_val_f1=0.4151 test_acc=0.4316 test_f1=0.3277 test_auc=0.5122

openai_clip k=1 seed=5:  28%|██▊       | 28/100 [00:51<02:12,  1.84s/it, best=0.4076, head_lr=8.1e-04, lora_lr=8.1e-05, loss=0.6408, val_f1=0.3248]

done model=openai_clip k=1 seed=5 best_epoch=11 best_val_f1=0.4076 test_acc=0.5158 test_f1=0.4857 test_auc=0.6159

openai_clip k=1 seed=6:  22%|██▏       | 22/100 [00:41<02:26,  1.88s/it, best=0.4956, head_lr=8.8e-04, lora_lr=8.8e-05, loss=0.7506, val_f1=0.3772]

done model=openai_clip k=1 seed=6 best_epoch=5 best_val_f1=0.4956 test_acc=0.5053 test_f1=0.3835 test_auc=0.6349

openai_clip k=1 seed=7:  93%|█████████▎| 93/100 [02:49<00:12,  1.83s/it, best=0.4900, head_lr=9.0e-06, lora_lr=9.8e-07, loss=0.3195, val_f1=0.4801]

done model=openai_clip k=1 seed=7 best_epoch=76 best_val_f1=0.4900 test_acc=0.5368 test_f1=0.5165 test_auc=0.7667

openai_clip k=1 seed=8:  29%|██▉       | 29/100 [00:53<02:11,  1.85s/it, best=0.4258, head_lr=7.9e-04, lora_lr=7.9e-05, loss=0.6324, val_f1=0.3890]

done model=openai_clip k=1 seed=8 best_epoch=12 best_val_f1=0.4258 test_acc=0.3895 test_f1=0.3323 test_auc=0.5939

openai_clip k=1 seed=9:  25%|██▌       | 25/100 [00:46<02:20,  1.88s/it, best=0.4090, head_lr=8.4e-04, lora_lr=8.4e-05, loss=0.6993, val_f1=0.2293]

done model=openai_clip k=1 seed=9 best_epoch=8 best_val_f1=0.4090 test_acc=0.3474 test_f1=0.2718 test_auc=0.5369

openai_clip k=1 seed=10:  28%|██▊       | 28/100 [00:51<02:13,  1.85s/it, best=0.3298, head_lr=8.1e-04, lora_lr=8.1e-05, loss=0.6469, val_f1=0.2277]

done model=openai_clip k=1 seed=10 best_epoch=11 best_val_f1=0.3298 test_acc=0.3263 test_f1=0.2993 test_auc=0.5411

openai_clip k=2 seed=1:  61%|██████    | 61/100 [01:51<01:11,  1.83s/it, best=0.5097, head_lr=3.2e-04, lora_lr=3.2e-05, loss=0.3603, val_f1=0.4595]

done model=openai_clip k=2 seed=1 best_epoch=44 best_val_f1=0.5097 test_acc=0.2421 test_f1=0.2408 test_auc=0.5292

openai_clip k=2 seed=2:  20%|██        | 20/100 [00:37<02:29,  1.87s/it, best=0.3722, head_lr=9.0e-04, lora_lr=9.0e-05, loss=0.8030, val_f1=0.1938]

done model=openai_clip k=2 seed=2 best_epoch=3 best_val_f1=0.3722 test_acc=0.2737 test_f1=0.2470 test_auc=0.5176

openai_clip k=2 seed=3:  26%|██▌       | 26/100 [00:47<02:16,  1.84s/it, best=0.2704, head_lr=8.3e-04, lora_lr=8.3e-05, loss=0.6959, val_f1=0.2219]

done model=openai_clip k=2 seed=3 best_epoch=9 best_val_f1=0.2704 test_acc=0.3684 test_f1=0.3464 test_auc=0.4931

openai_clip k=2 seed=4:  59%|█████▉    | 59/100 [01:49<01:15,  1.85s/it, best=0.4263, head_lr=3.5e-04, lora_lr=3.5e-05, loss=0.3760, val_f1=0.4108]

done model=openai_clip k=2 seed=4 best_epoch=42 best_val_f1=0.4263 test_acc=0.4105 test_f1=0.3340 test_auc=0.6740

openai_clip k=2 seed=5:  25%|██▌       | 25/100 [00:47<02:21,  1.89s/it, best=0.3181, head_lr=8.4e-04, lora_lr=8.4e-05, loss=0.7370, val_f1=0.3025]

done model=openai_clip k=2 seed=5 best_epoch=8 best_val_f1=0.3181 test_acc=0.2632 test_f1=0.2488 test_auc=0.5231

openai_clip k=2 seed=6:  21%|██        | 21/100 [00:39<02:27,  1.87s/it, best=0.4570, head_lr=8.9e-04, lora_lr=8.9e-05, loss=0.7830, val_f1=0.4150]

done model=openai_clip k=2 seed=6 best_epoch=4 best_val_f1=0.4570 test_acc=0.4421 test_f1=0.2873 test_auc=0.5489

openai_clip k=2 seed=7:  61%|██████    | 61/100 [01:50<01:10,  1.82s/it, best=0.4743, head_lr=3.2e-04, lora_lr=3.2e-05, loss=0.3719, val_f1=0.4173]

done model=openai_clip k=2 seed=7 best_epoch=44 best_val_f1=0.4743 test_acc=0.5263 test_f1=0.4857 test_auc=0.7786

openai_clip k=2 seed=8:  25%|██▌       | 25/100 [00:46<02:18,  1.85s/it, best=0.4187, head_lr=8.4e-04, lora_lr=8.4e-05, loss=0.7283, val_f1=0.3422]

done model=openai_clip k=2 seed=8 best_epoch=8 best_val_f1=0.4187 test_acc=0.4421 test_f1=0.2981 test_auc=0.6135

openai_clip k=2 seed=9:  35%|███▌      | 35/100 [01:04<02:00,  1.85s/it, best=0.4482, head_lr=7.1e-04, lora_lr=7.1e-05, loss=0.5883, val_f1=0.4106]

done model=openai_clip k=2 seed=9 best_epoch=18 best_val_f1=0.4482 test_acc=0.4211 test_f1=0.4296 test_auc=0.6354

openai_clip k=2 seed=10:  27%|██▋       | 27/100 [00:50<02:16,  1.87s/it, best=0.5054, head_lr=8.2e-04, lora_lr=8.2e-05, loss=0.6932, val_f1=0.4329]

done model=openai_clip k=2 seed=10 best_epoch=10 best_val_f1=0.5054 test_acc=0.4316 test_f1=0.4178 test_auc=0.6890

openai_clip k=4 seed=1:  82%|████████▏ | 82/100 [02:44<00:36,  2.00s/it, best=0.6022, head_lr=7.0e-05, lora_lr=7.1e-06, loss=0.3570, val_f1=0.5989]

done model=openai_clip k=4 seed=1 best_epoch=65 best_val_f1=0.6022 test_acc=0.4737 test_f1=0.4666 test_auc=0.7594

openai_clip k=4 seed=2:  40%|████      | 40/100 [01:18<01:57,  1.96s/it, best=0.4847, head_lr=6.4e-04, lora_lr=6.4e-05, loss=0.5848, val_f1=0.4454]

done model=openai_clip k=4 seed=2 best_epoch=23 best_val_f1=0.4847 test_acc=0.4526 test_f1=0.4471 test_auc=0.6889

openai_clip k=4 seed=3:  31%|███       | 31/100 [00:59<02:12,  1.92s/it, best=0.5589, head_lr=7.7e-04, lora_lr=7.7e-05, loss=0.6867, val_f1=0.4615]

done model=openai_clip k=4 seed=3 best_epoch=14 best_val_f1=0.5589 test_acc=0.5053 test_f1=0.4962 test_auc=0.7309

openai_clip k=4 seed=4:  35%|███▌      | 35/100 [01:07<02:05,  1.93s/it, best=0.6462, head_lr=7.1e-04, lora_lr=7.1e-05, loss=0.6142, val_f1=0.4184]

done model=openai_clip k=4 seed=4 best_epoch=18 best_val_f1=0.6462 test_acc=0.6947 test_f1=0.6348 test_auc=0.8115

openai_clip k=4 seed=5:  37%|███▋      | 37/100 [01:09<01:58,  1.89s/it, best=0.5342, head_lr=6.8e-04, lora_lr=6.8e-05, loss=0.6391, val_f1=0.5131]

done model=openai_clip k=4 seed=5 best_epoch=20 best_val_f1=0.5342 test_acc=0.4421 test_f1=0.4487 test_auc=0.6858

openai_clip k=4 seed=6:  31%|███       | 31/100 [01:00<02:13,  1.94s/it, best=0.5428, head_lr=7.7e-04, lora_lr=7.7e-05, loss=0.6746, val_f1=0.4118]

done model=openai_clip k=4 seed=6 best_epoch=14 best_val_f1=0.5428 test_acc=0.3684 test_f1=0.3582 test_auc=0.6439

openai_clip k=4 seed=7:  48%|████▊     | 48/100 [01:30<01:38,  1.90s/it, best=0.5952, head_lr=5.2e-04, lora_lr=5.2e-05, loss=0.4810, val_f1=0.5527]

done model=openai_clip k=4 seed=7 best_epoch=31 best_val_f1=0.5952 test_acc=0.6211 test_f1=0.5824 test_auc=0.8073

openai_clip k=4 seed=8:  24%|██▍       | 24/100 [00:46<02:26,  1.93s/it, best=0.6074, head_lr=8.5e-04, lora_lr=8.5e-05, loss=0.7865, val_f1=0.5023]

done model=openai_clip k=4 seed=8 best_epoch=7 best_val_f1=0.6074 test_acc=0.6421 test_f1=0.5749 test_auc=0.7558

openai_clip k=4 seed=9:  59%|█████▉    | 59/100 [01:50<01:17,  1.88s/it, best=0.5463, head_lr=3.5e-04, lora_lr=3.5e-05, loss=0.4459, val_f1=0.5150]

done model=openai_clip k=4 seed=9 best_epoch=42 best_val_f1=0.5463 test_acc=0.5895 test_f1=0.5160 test_auc=0.7005

openai_clip k=4 seed=10:  25%|██▌       | 25/100 [00:48<02:24,  1.93s/it, best=0.4929, head_lr=8.4e-04, lora_lr=8.4e-05, loss=0.7867, val_f1=0.4725]

done model=openai_clip k=4 seed=10 best_epoch=8 best_val_f1=0.4929 test_acc=0.5053 test_f1=0.3865 test_auc=0.7134

openai_clip k=8 seed=1:  29%|██▉       | 29/100 [01:04<02:37,  2.22s/it, best=0.6539, head_lr=7.9e-04, lora_lr=7.9e-05, loss=0.6867, val_f1=0.5992]

done model=openai_clip k=8 seed=1 best_epoch=12 best_val_f1=0.6539 test_acc=0.5895 test_f1=0.5827 test_auc=0.7699

openai_clip k=8 seed=2:  67%|██████▋   | 67/100 [02:22<01:10,  2.13s/it, best=0.6518, head_lr=2.3e-04, lora_lr=2.3e-05, loss=0.3684, val_f1=0.6518]

done model=openai_clip k=8 seed=2 best_epoch=50 best_val_f1=0.6518 test_acc=0.5368 test_f1=0.5363 test_auc=0.8235

openai_clip k=8 seed=3:  73%|███████▎  | 73/100 [02:37<00:58,  2.16s/it, best=0.5237, head_lr=1.6e-04, lora_lr=1.6e-05, loss=0.3401, val_f1=0.5237]

done model=openai_clip k=8 seed=3 best_epoch=56 best_val_f1=0.5237 test_acc=0.6421 test_f1=0.6231 test_auc=0.8279

openai_clip k=8 seed=4:  57%|█████▋    | 57/100 [02:02<01:32,  2.15s/it, best=0.6935, head_lr=3.8e-04, lora_lr=3.8e-05, loss=0.4120, val_f1=0.6437]

done model=openai_clip k=8 seed=4 best_epoch=40 best_val_f1=0.6935 test_acc=0.6632 test_f1=0.6555 test_auc=0.8664

openai_clip k=8 seed=5:  59%|█████▉    | 59/100 [02:08<01:28,  2.17s/it, best=0.6773, head_lr=3.5e-04, lora_lr=3.5e-05, loss=0.4071, val_f1=0.6330]

done model=openai_clip k=8 seed=5 best_epoch=42 best_val_f1=0.6773 test_acc=0.6421 test_f1=0.6075 test_auc=0.7710

openai_clip k=8 seed=6:  53%|█████▎    | 53/100 [01:55<01:42,  2.18s/it, best=0.6310, head_lr=4.4e-04, lora_lr=4.4e-05, loss=0.4314, val_f1=0.5954]

done model=openai_clip k=8 seed=6 best_epoch=36 best_val_f1=0.6310 test_acc=0.5579 test_f1=0.5515 test_auc=0.7457

openai_clip k=8 seed=7:  38%|███▊      | 38/100 [01:23<02:16,  2.20s/it, best=0.6162, head_lr=6.7e-04, lora_lr=6.7e-05, loss=0.5859, val_f1=0.5377]

done model=openai_clip k=8 seed=7 best_epoch=21 best_val_f1=0.6162 test_acc=0.7053 test_f1=0.7176 test_auc=0.8663

openai_clip k=8 seed=8:  23%|██▎       | 23/100 [00:51<02:51,  2.23s/it, best=0.5674, head_lr=8.6e-04, lora_lr=8.6e-05, loss=0.8190, val_f1=0.5064]

done model=openai_clip k=8 seed=8 best_epoch=6 best_val_f1=0.5674 test_acc=0.5579 test_f1=0.5072 test_auc=0.7200

openai_clip k=8 seed=9:  34%|███▍      | 34/100 [01:14<02:23,  2.18s/it, best=0.5222, head_lr=7.3e-04, lora_lr=7.3e-05, loss=0.6532, val_f1=0.5193]

done model=openai_clip k=8 seed=9 best_epoch=17 best_val_f1=0.5222 test_acc=0.5579 test_f1=0.5093 test_auc=0.7145

openai_clip k=8 seed=10:  90%|█████████ | 90/100 [03:14<00:21,  2.16s/it, best=0.7111, head_lr=2.0e-05, lora_lr=2.1e-06, loss=0.3323, val_f1=0.6812]

done model=openai_clip k=8 seed=10 best_epoch=73 best_val_f1=0.7111 test_acc=0.6211 test_f1=0.6057 test_auc=0.8019

openai_clip k=16 seed=1:  41%|████      | 41/100 [01:52<02:42,  2.76s/it, best=0.7682, head_lr=6.2e-04, lora_lr=6.2e-05, loss=0.2587, val_f1=0.7190]

done model=openai_clip k=16 seed=1 best_epoch=24 best_val_f1=0.7682 test_acc=0.6947 test_f1=0.6849 test_auc=0.8743

openai_clip k=16 seed=2:  57%|█████▋    | 57/100 [02:37<01:58,  2.76s/it, best=0.6641, head_lr=3.8e-04, lora_lr=3.8e-05, loss=0.1883, val_f1=0.6389]

done model=openai_clip k=16 seed=2 best_epoch=40 best_val_f1=0.6641 test_acc=0.6211 test_f1=0.6117 test_auc=0.8135

openai_clip k=16 seed=3:  53%|█████▎    | 53/100 [02:23<02:07,  2.71s/it, best=0.6690, head_lr=4.4e-04, lora_lr=4.4e-05, loss=0.1867, val_f1=0.6257]

done model=openai_clip k=16 seed=3 best_epoch=36 best_val_f1=0.6690 test_acc=0.6526 test_f1=0.6152 test_auc=0.8240

openai_clip k=16 seed=4:  34%|███▍      | 34/100 [01:35<03:05,  2.81s/it, best=0.7421, head_lr=7.3e-04, lora_lr=7.3e-05, loss=0.3336, val_f1=0.6937]

done model=openai_clip k=16 seed=4 best_epoch=17 best_val_f1=0.7421 test_acc=0.6842 test_f1=0.6855 test_auc=0.8308

openai_clip k=16 seed=5:  39%|███▉      | 39/100 [01:49<02:52,  2.82s/it, best=0.7004, head_lr=6.5e-04, lora_lr=6.5e-05, loss=0.3060, val_f1=0.6951]

done model=openai_clip k=16 seed=5 best_epoch=22 best_val_f1=0.7004 test_acc=0.6211 test_f1=0.6219 test_auc=0.8190

openai_clip k=16 seed=6:  28%|██▊       | 28/100 [01:17<03:19,  2.77s/it, best=0.7225, head_lr=8.1e-04, lora_lr=8.1e-05, loss=0.4315, val_f1=0.6589]

done model=openai_clip k=16 seed=6 best_epoch=11 best_val_f1=0.7225 test_acc=0.7158 test_f1=0.6969 test_auc=0.8341

openai_clip k=16 seed=7:  64%|██████▍   | 64/100 [02:56<01:39,  2.76s/it, best=0.7522, head_lr=2.7e-04, lora_lr=2.7e-05, loss=0.1560, val_f1=0.7210]

done model=openai_clip k=16 seed=7 best_epoch=47 best_val_f1=0.7522 test_acc=0.8211 test_f1=0.8129 test_auc=0.9130

openai_clip k=16 seed=8:  46%|████▌     | 46/100 [02:06<02:28,  2.76s/it, best=0.6463, head_lr=5.5e-04, lora_lr=5.5e-05, loss=0.2310, val_f1=0.6324]

done model=openai_clip k=16 seed=8 best_epoch=29 best_val_f1=0.6463 test_acc=0.6632 test_f1=0.6413 test_auc=0.7990

openai_clip k=16 seed=9:  33%|███▎      | 33/100 [01:34<03:11,  2.86s/it, best=0.7720, head_lr=7.4e-04, lora_lr=7.4e-05, loss=0.3476, val_f1=0.6622]

done model=openai_clip k=16 seed=9 best_epoch=16 best_val_f1=0.7720 test_acc=0.6947 test_f1=0.6868 test_auc=0.8555

openai_clip k=16 seed=10:  78%|███████▊  | 78/100 [03:38<01:01,  2.80s/it, best=0.7252, head_lr=1.1e-04, lora_lr=1.1e-05, loss=0.1303, val_f1=0.7147]

done model=openai_clip k=16 seed=10 best_epoch=61 best_val_f1=0.7252 test_acc=0.7895 test_f1=0.7691 test_auc=0.8980

openai_clip k=32 seed=1:  44%|████▍     | 44/100 [02:58<03:46,  4.05s/it, best=0.8432, head_lr=5.8e-04, lora_lr=5.8e-05, loss=0.1007, val_f1=0.7825]

done model=openai_clip k=32 seed=1 best_epoch=27 best_val_f1=0.8432 test_acc=0.7684 test_f1=0.7512 test_auc=0.8970

openai_clip k=32 seed=2:  62%|██████▏   | 62/100 [04:05<02:30,  3.96s/it, best=0.8106, head_lr=3.0e-04, lora_lr=3.0e-05, loss=0.0593, val_f1=0.7853]

done model=openai_clip k=32 seed=2 best_epoch=45 best_val_f1=0.8106 test_acc=0.7263 test_f1=0.7267 test_auc=0.8829

openai_clip k=32 seed=3:  40%|████      | 40/100 [02:41<04:01,  4.03s/it, best=0.7348, head_lr=6.4e-04, lora_lr=6.4e-05, loss=0.1180, val_f1=0.6957]

done model=openai_clip k=32 seed=3 best_epoch=23 best_val_f1=0.7348 test_acc=0.7053 test_f1=0.6841 test_auc=0.8552

openai_clip k=32 seed=4:  37%|███▋      | 37/100 [02:30<04:16,  4.07s/it, best=0.8023, head_lr=6.8e-04, lora_lr=6.8e-05, loss=0.1606, val_f1=0.7801]

done model=openai_clip k=32 seed=4 best_epoch=20 best_val_f1=0.8023 test_acc=0.7684 test_f1=0.7786 test_auc=0.9281

openai_clip k=32 seed=5:  38%|███▊      | 38/100 [02:32<04:08,  4.00s/it, best=0.7812, head_lr=6.7e-04, lora_lr=6.7e-05, loss=0.1333, val_f1=0.7245]

done model=openai_clip k=32 seed=5 best_epoch=21 best_val_f1=0.7812 test_acc=0.7368 test_f1=0.7420 test_auc=0.8916

openai_clip k=32 seed=6:  40%|████      | 40/100 [02:41<04:02,  4.04s/it, best=0.8074, head_lr=6.4e-04, lora_lr=6.4e-05, loss=0.1107, val_f1=0.7761]

done model=openai_clip k=32 seed=6 best_epoch=23 best_val_f1=0.8074 test_acc=0.7368 test_f1=0.7260 test_auc=0.8738

openai_clip k=32 seed=7:  43%|████▎     | 43/100 [02:51<03:47,  3.99s/it, best=0.7514, head_lr=5.9e-04, lora_lr=5.9e-05, loss=0.1112, val_f1=0.7185]

done model=openai_clip k=32 seed=7 best_epoch=26 best_val_f1=0.7514 test_acc=0.7579 test_f1=0.7504 test_auc=0.8845

openai_clip k=32 seed=8:  54%|█████▍    | 54/100 [03:36<03:04,  4.00s/it, best=0.7627, head_lr=4.2e-04, lora_lr=4.2e-05, loss=0.0654, val_f1=0.7407]

done model=openai_clip k=32 seed=8 best_epoch=37 best_val_f1=0.7627 test_acc=0.7053 test_f1=0.6820 test_auc=0.8666

openai_clip k=32 seed=9:  37%|███▋      | 37/100 [02:30<04:15,  4.06s/it, best=0.7524, head_lr=6.8e-04, lora_lr=6.8e-05, loss=0.1494, val_f1=0.7173]

done model=openai_clip k=32 seed=9 best_epoch=20 best_val_f1=0.7524 test_acc=0.8105 test_f1=0.7986 test_auc=0.8983

openai_clip k=32 seed=10:  44%|████▍     | 44/100 [02:55<03:43,  3.99s/it, best=0.7859, head_lr=5.8e-04, lora_lr=5.8e-05, loss=0.1079, val_f1=0.7697]

done model=openai_clip k=32 seed=10 best_epoch=27 best_val_f1=0.7859 test_acc=0.7158 test_f1=0.7113 test_auc=0.8912

LoRA summary:
 k  best_epoch_mean  best_val_macro_f1_mean  best_val_macro_f1_std  test_accuracy_mean  test_accuracy_std  test_macro_f1_mean  test_macro_f1_std  test_auc_mean  test_auc_std
 1             19.4                0.415706               0.070930            0.409474           0.093025            0.359189           0.089457       0.584313      0.079520
 2             19.0                0.420040               0.078567            0.382105           0.093369            0.333550           0.085836       0.600250      0.093395
 4             24.2                0.561091               0.051646            0.529474           0.103142            0.491155           0.087925       0.729743      0.054109
 8             35.3                0.624828               0.067207            0.607368           0.055711            0.589619           0.066672       0.790719      0.055453
16             30.3                0.716215               0.044689            0.695789           0.065915            0.682602           0.066368       0.846113      0.037890
32             26.9                0.783172               0.033394            0.743158           0.033361            0.735095           0.037416       0.886924      0.019947

,k,best_epoch_mean,best_val_macro_f1_mean,best_val_macro_f1_std,test_accuracy_mean,test_accuracy_std,test_macro_f1_mean,test_macro_f1_std,test_auc_mean,test_auc_std
0,1,19.4,0.415706,0.070930,0.409474,0.093025,0.359189,0.089457,0.584313,0.079520
1,2,19.0,0.420040,0.078567,0.382105,0.093369,0.333550,0.085836,0.600250,0.093395
2,4,24.2,0.561091,0.051646,0.529474,0.103142,0.491155,0.087925,0.729743,0.054109
3,8,35.3,0.624828,0.067207,0.607368,0.055711,0.589619,0.066672,0.790719,0.055453
4,16,30.3,0.716215,0.044689,0.695789,0.065915,0.682602,0.066368,0.846113,0.037890
5,32,26.9,0.783172,0.033394,0.743158,0.033361,0.735095,0.037416,0.886924,0.019947

Few-Shot LoRA Fine-Tuning using BiomedCLIP ViT-B/16

In [15]:
# Run LoRA training for BiomedCLIP.
args = get_args([])
args.console_log = False
args.show_progress = True
args.log_epochs = False
args.log_train_metrics = False

args.model_name = 'biomedclip_vit_b16'
args.device = device
args.num_classes = len(busi_classes)
args.encoder = 'vision'

# Training knobs.
args.epochs = 100
args.batch_size = 8
args.accumulation_steps = 4
args.patience = 18
args.grad_clip = 1.0

# Optimizer knobs.
args.lr = 1e-4
args.head_lr = 1e-3
args.lora_lr = 1e-4
args.lr_min = 1e-7
args.head_weight_decay = 1e-3
args.lora_weight_decay = 1e-5

# LoRA knobs.
args.lora_layers = None
args.lora_rank = 16
args.lora_alpha = 32
args.lora_dropout = 0.1

# Target fused qkv and output projection for fair comparison with OpenAI CLIP q + k + v + o.
args.biomed_lora_targets = ['qkv', 'proj']

# Use eval preprocessing during LoRA training for a controlled few-shot comparison.
args.use_eval_preprocess_for_train = False

save_dir = lora_base_save_dir / args.model_name

biomedclip_lora_results_df, biomedclip_lora_summary_df = run_kshot_experiments(
    args=args,
    train_df=train_df,
    val_df=val_df,
    test_df=test_df,
    class_names=lora_class_names,
    ks=shots_per_class,
    seeds=seeds,
    save_dir=save_dir,
    support_indices=shared_support_indices,
)

biomedclip_lora_summary_df

LoRA few-shot: model=biomedclip | k=[1, 2, 4, 8, 16, 32] | seeds=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10] | rank=16 | alpha=32 | dropout=0.1 | layers=None
trainable params: 884,736 || all params: 196,787,457 || trainable%: 0.4496

LoRA model check: biomedclip
  trainable vision tensors: 48
  vision trainable params: 884,736 / 196,787,457
  classifier trainable params: 1,539
  total trainable params: 886,275

biomedclip k=1 seed=1:  73%|███████▎  | 73/100 [01:55<00:42,  1.59s/it, best=0.4684, head_lr=1.6e-04, lora_lr=1.6e-05, loss=0.4240, val_f1=0.3808]

done model=biomedclip k=1 seed=1 best_epoch=56 best_val_f1=0.4684 test_acc=0.5263 test_f1=0.3749 test_auc=0.5962

biomedclip k=1 seed=2:  72%|███████▏  | 72/100 [01:52<00:43,  1.56s/it, best=0.3846, head_lr=1.7e-04, lora_lr=1.7e-05, loss=0.4527, val_f1=0.3797]

done model=biomedclip k=1 seed=2 best_epoch=55 best_val_f1=0.3846 test_acc=0.4211 test_f1=0.3061 test_auc=0.5484

biomedclip k=1 seed=3:  30%|███       | 30/100 [00:48<01:54,  1.63s/it, best=0.3802, head_lr=7.8e-04, lora_lr=7.8e-05, loss=0.7378, val_f1=0.3327]

done model=biomedclip k=1 seed=3 best_epoch=13 best_val_f1=0.3802 test_acc=0.4526 test_f1=0.3999 test_auc=0.5939

biomedclip k=1 seed=4:  67%|██████▋   | 67/100 [01:47<00:53,  1.61s/it, best=0.5671, head_lr=2.3e-04, lora_lr=2.3e-05, loss=0.4390, val_f1=0.4994]

done model=biomedclip k=1 seed=4 best_epoch=50 best_val_f1=0.5671 test_acc=0.5053 test_f1=0.4678 test_auc=0.6800

biomedclip k=1 seed=5:  25%|██▌       | 25/100 [00:41<02:03,  1.65s/it, best=0.5930, head_lr=8.4e-04, lora_lr=8.4e-05, loss=0.8515, val_f1=0.4662]

done model=biomedclip k=1 seed=5 best_epoch=8 best_val_f1=0.5930 test_acc=0.5789 test_f1=0.5633 test_auc=0.7166

biomedclip k=1 seed=6:  39%|███▉      | 39/100 [01:02<01:37,  1.60s/it, best=0.6265, head_lr=6.5e-04, lora_lr=6.5e-05, loss=0.6741, val_f1=0.4458]

done model=biomedclip k=1 seed=6 best_epoch=22 best_val_f1=0.6265 test_acc=0.5684 test_f1=0.5404 test_auc=0.7821

biomedclip k=1 seed=7:  55%|█████▌    | 55/100 [01:28<01:12,  1.62s/it, best=0.5079, head_lr=4.1e-04, lora_lr=4.1e-05, loss=0.4738, val_f1=0.4737]

done model=biomedclip k=1 seed=7 best_epoch=38 best_val_f1=0.5079 test_acc=0.4737 test_f1=0.4678 test_auc=0.7854

biomedclip k=1 seed=8:  31%|███       | 31/100 [00:57<02:06,  1.84s/it, best=0.4115, head_lr=7.7e-04, lora_lr=7.7e-05, loss=0.7317, val_f1=0.3884]

done model=biomedclip k=1 seed=8 best_epoch=14 best_val_f1=0.4115 test_acc=0.5263 test_f1=0.3973 test_auc=0.6932

biomedclip k=1 seed=9:  50%|█████     | 50/100 [01:40<01:40,  2.01s/it, best=0.3362, head_lr=4.8e-04, lora_lr=4.8e-05, loss=0.5662, val_f1=0.2848]

done model=biomedclip k=1 seed=9 best_epoch=33 best_val_f1=0.3362 test_acc=0.3053 test_f1=0.3686 test_auc=0.5683

'[Errno 11001] getaddrinfo failed' thrown while requesting HEAD https://huggingface.co/microsoft/BiomedCLIP-PubMedBERT_256-vit_base_patch16_224/resolve/main/open_clip_model.safetensors
WARNING:huggingface_hub.utils._http:'[Errno 11001] getaddrinfo failed' thrown while requesting HEAD https://huggingface.co/microsoft/BiomedCLIP-PubMedBERT_256-vit_base_patch16_224/resolve/main/open_clip_model.safetensors
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].
biomedclip k=1 seed=10:  45%|████▌     | 45/100 [01:31<01:51,  2.03s/it, best=0.4481, head_lr=5.6e-04, lora_lr=5.6e-05, loss=0.5890, val_f1=0.3301]

done model=biomedclip k=1 seed=10 best_epoch=28 best_val_f1=0.4481 test_acc=0.4421 test_f1=0.4404 test_auc=0.7320

biomedclip k=2 seed=1:  49%|████▉     | 49/100 [01:43<01:47,  2.11s/it, best=0.5905, head_lr=5.0e-04, lora_lr=5.0e-05, loss=0.6194, val_f1=0.5794]

done model=biomedclip k=2 seed=1 best_epoch=32 best_val_f1=0.5905 test_acc=0.5368 test_f1=0.5299 test_auc=0.7701

biomedclip k=2 seed=2:  63%|██████▎   | 63/100 [02:11<01:17,  2.09s/it, best=0.5995, head_lr=2.9e-04, lora_lr=2.9e-05, loss=0.5151, val_f1=0.5686]

done model=biomedclip k=2 seed=2 best_epoch=46 best_val_f1=0.5995 test_acc=0.5789 test_f1=0.5685 test_auc=0.8128

biomedclip k=2 seed=3:  22%|██▏       | 22/100 [00:46<02:45,  2.12s/it, best=0.2533, head_lr=8.8e-04, lora_lr=8.8e-05, loss=0.8931, val_f1=0.1771]

done model=biomedclip k=2 seed=3 best_epoch=5 best_val_f1=0.2533 test_acc=0.3158 test_f1=0.2833 test_auc=0.4496

biomedclip k=2 seed=4:  78%|███████▊  | 78/100 [02:39<00:45,  2.05s/it, best=0.6487, head_lr=1.1e-04, lora_lr=1.1e-05, loss=0.4394, val_f1=0.6221]

done model=biomedclip k=2 seed=4 best_epoch=61 best_val_f1=0.6487 test_acc=0.6737 test_f1=0.6511 test_auc=0.7969

biomedclip k=2 seed=5:  23%|██▎       | 23/100 [00:48<02:42,  2.11s/it, best=0.4300, head_lr=8.6e-04, lora_lr=8.6e-05, loss=0.9001, val_f1=0.3597]

done model=biomedclip k=2 seed=5 best_epoch=6 best_val_f1=0.4300 test_acc=0.3684 test_f1=0.3489 test_auc=0.5715

biomedclip k=2 seed=6:  63%|██████▎   | 63/100 [02:09<01:16,  2.06s/it, best=0.6915, head_lr=2.9e-04, lora_lr=2.9e-05, loss=0.4842, val_f1=0.6622]

done model=biomedclip k=2 seed=6 best_epoch=46 best_val_f1=0.6915 test_acc=0.6105 test_f1=0.6204 test_auc=0.7927

biomedclip k=2 seed=7:  46%|████▌     | 46/100 [01:34<01:51,  2.06s/it, best=0.5444, head_lr=5.5e-04, lora_lr=5.5e-05, loss=0.5911, val_f1=0.5414]

done model=biomedclip k=2 seed=7 best_epoch=29 best_val_f1=0.5444 test_acc=0.6105 test_f1=0.5431 test_auc=0.7863

biomedclip k=2 seed=8:  72%|███████▏  | 72/100 [02:29<00:58,  2.08s/it, best=0.7524, head_lr=1.7e-04, lora_lr=1.7e-05, loss=0.4642, val_f1=0.7238]

done model=biomedclip k=2 seed=8 best_epoch=55 best_val_f1=0.7524 test_acc=0.7368 test_f1=0.7139 test_auc=0.8807

biomedclip k=2 seed=9:  25%|██▌       | 25/100 [00:53<02:39,  2.12s/it, best=0.4040, head_lr=8.4e-04, lora_lr=8.4e-05, loss=0.8958, val_f1=0.3266]

done model=biomedclip k=2 seed=9 best_epoch=8 best_val_f1=0.4040 test_acc=0.4000 test_f1=0.4135 test_auc=0.6549

biomedclip k=2 seed=10:  21%|██        | 21/100 [00:45<02:52,  2.18s/it, best=0.5126, head_lr=8.9e-04, lora_lr=8.9e-05, loss=0.9393, val_f1=0.4919]

done model=biomedclip k=2 seed=10 best_epoch=4 best_val_f1=0.5126 test_acc=0.4737 test_f1=0.4713 test_auc=0.6735

biomedclip k=4 seed=1:  49%|████▉     | 49/100 [01:55<01:59,  2.35s/it, best=0.7006, head_lr=5.0e-04, lora_lr=5.0e-05, loss=0.6952, val_f1=0.6827]

done model=biomedclip k=4 seed=1 best_epoch=32 best_val_f1=0.7006 test_acc=0.6842 test_f1=0.6849 test_auc=0.8538

biomedclip k=4 seed=2:  78%|███████▊  | 78/100 [03:03<00:51,  2.35s/it, best=0.6543, head_lr=1.1e-04, lora_lr=1.1e-05, loss=0.4715, val_f1=0.6543]

done model=biomedclip k=4 seed=2 best_epoch=61 best_val_f1=0.6543 test_acc=0.5895 test_f1=0.5727 test_auc=0.8278

biomedclip k=4 seed=3:  63%|██████▎   | 63/100 [02:30<01:28,  2.39s/it, best=0.7708, head_lr=2.9e-04, lora_lr=2.9e-05, loss=0.5767, val_f1=0.7290]

done model=biomedclip k=4 seed=3 best_epoch=46 best_val_f1=0.7708 test_acc=0.7684 test_f1=0.7653 test_auc=0.8602

biomedclip k=4 seed=4:  61%|██████    | 61/100 [02:23<01:31,  2.35s/it, best=0.7954, head_lr=3.2e-04, lora_lr=3.2e-05, loss=0.5352, val_f1=0.7321]

done model=biomedclip k=4 seed=4 best_epoch=44 best_val_f1=0.7954 test_acc=0.7263 test_f1=0.7200 test_auc=0.8966

biomedclip k=4 seed=5:  18%|█▊        | 18/100 [00:44<03:20,  2.45s/it, best=0.2921, head_lr=9.1e-04, lora_lr=9.1e-05, loss=1.0227, val_f1=0.2238]

done model=biomedclip k=4 seed=5 best_epoch=1 best_val_f1=0.2921 test_acc=0.3158 test_f1=0.2594 test_auc=0.5498

biomedclip k=4 seed=6:  74%|███████▍  | 74/100 [02:51<01:00,  2.32s/it, best=0.6098, head_lr=1.5e-04, lora_lr=1.5e-05, loss=0.5040, val_f1=0.5794]

done model=biomedclip k=4 seed=6 best_epoch=57 best_val_f1=0.6098 test_acc=0.5895 test_f1=0.6135 test_auc=0.8217

biomedclip k=4 seed=7:  77%|███████▋  | 77/100 [02:59<00:53,  2.33s/it, best=0.6940, head_lr=1.1e-04, lora_lr=1.2e-05, loss=0.4882, val_f1=0.6940]

done model=biomedclip k=4 seed=7 best_epoch=60 best_val_f1=0.6940 test_acc=0.6211 test_f1=0.6215 test_auc=0.7929

biomedclip k=4 seed=8:  37%|███▋      | 37/100 [01:28<02:30,  2.40s/it, best=0.6860, head_lr=6.8e-04, lora_lr=6.8e-05, loss=0.7477, val_f1=0.6574]

done model=biomedclip k=4 seed=8 best_epoch=20 best_val_f1=0.6860 test_acc=0.7053 test_f1=0.6867 test_auc=0.8836

biomedclip k=4 seed=9:  66%|██████▌   | 66/100 [02:48<01:26,  2.56s/it, best=0.6259, head_lr=2.5e-04, lora_lr=2.5e-05, loss=0.6056, val_f1=0.5987]

done model=biomedclip k=4 seed=9 best_epoch=49 best_val_f1=0.6259 test_acc=0.5684 test_f1=0.5371 test_auc=0.7901

biomedclip k=4 seed=10:  23%|██▎       | 23/100 [00:44<02:28,  1.93s/it, best=0.5442, head_lr=8.6e-04, lora_lr=8.6e-05, loss=0.9419, val_f1=0.3597]

done model=biomedclip k=4 seed=10 best_epoch=6 best_val_f1=0.5442 test_acc=0.5579 test_f1=0.5042 test_auc=0.7544

biomedclip k=8 seed=1:  63%|██████▎   | 63/100 [02:17<01:20,  2.18s/it, best=0.6796, head_lr=2.9e-04, lora_lr=2.9e-05, loss=0.5049, val_f1=0.6263]

done model=biomedclip k=8 seed=1 best_epoch=46 best_val_f1=0.6796 test_acc=0.6421 test_f1=0.6389 test_auc=0.8267

biomedclip k=8 seed=2:  68%|██████▊   | 68/100 [02:26<01:08,  2.15s/it, best=0.6608, head_lr=2.2e-04, lora_lr=2.2e-05, loss=0.4880, val_f1=0.6497]

done model=biomedclip k=8 seed=2 best_epoch=51 best_val_f1=0.6608 test_acc=0.7263 test_f1=0.7104 test_auc=0.8714

biomedclip k=8 seed=3:  37%|███▋      | 37/100 [01:21<02:18,  2.20s/it, best=0.6938, head_lr=6.8e-04, lora_lr=6.8e-05, loss=0.7570, val_f1=0.6824]

done model=biomedclip k=8 seed=3 best_epoch=20 best_val_f1=0.6938 test_acc=0.6737 test_f1=0.6692 test_auc=0.8784

biomedclip k=8 seed=4:  49%|████▉     | 49/100 [01:45<01:49,  2.15s/it, best=0.7467, head_lr=5.0e-04, lora_lr=5.0e-05, loss=0.6880, val_f1=0.7332]

done model=biomedclip k=8 seed=4 best_epoch=32 best_val_f1=0.7467 test_acc=0.7158 test_f1=0.6704 test_auc=0.8848

biomedclip k=8 seed=5:  49%|████▉     | 49/100 [01:47<01:52,  2.20s/it, best=0.8148, head_lr=5.0e-04, lora_lr=5.0e-05, loss=0.5869, val_f1=0.7713]

done model=biomedclip k=8 seed=5 best_epoch=32 best_val_f1=0.8148 test_acc=0.6737 test_f1=0.6658 test_auc=0.8480

biomedclip k=8 seed=6:  49%|████▉     | 49/100 [01:47<01:51,  2.18s/it, best=0.7095, head_lr=5.0e-04, lora_lr=5.0e-05, loss=0.6790, val_f1=0.6475]

done model=biomedclip k=8 seed=6 best_epoch=32 best_val_f1=0.7095 test_acc=0.6105 test_f1=0.6112 test_auc=0.8127

biomedclip k=8 seed=7:  52%|█████▏    | 52/100 [01:53<01:44,  2.18s/it, best=0.7321, head_lr=4.5e-04, lora_lr=4.5e-05, loss=0.6463, val_f1=0.7025]

done model=biomedclip k=8 seed=7 best_epoch=35 best_val_f1=0.7321 test_acc=0.6737 test_f1=0.6841 test_auc=0.8490

biomedclip k=8 seed=8:  24%|██▍       | 24/100 [00:52<02:46,  2.19s/it, best=0.6539, head_lr=8.5e-04, lora_lr=8.5e-05, loss=0.9686, val_f1=0.6505]

done model=biomedclip k=8 seed=8 best_epoch=7 best_val_f1=0.6539 test_acc=0.6421 test_f1=0.5896 test_auc=0.8144

biomedclip k=8 seed=9:  47%|████▋     | 47/100 [01:43<01:56,  2.20s/it, best=0.6640, head_lr=5.3e-04, lora_lr=5.3e-05, loss=0.6678, val_f1=0.6309]

done model=biomedclip k=8 seed=9 best_epoch=30 best_val_f1=0.6640 test_acc=0.7368 test_f1=0.7348 test_auc=0.8540

biomedclip k=8 seed=10:  55%|█████▌    | 55/100 [02:00<01:38,  2.19s/it, best=0.7444, head_lr=4.1e-04, lora_lr=4.1e-05, loss=0.6307, val_f1=0.7350]

done model=biomedclip k=8 seed=10 best_epoch=38 best_val_f1=0.7444 test_acc=0.6737 test_f1=0.6809 test_auc=0.8374

biomedclip k=16 seed=1:  26%|██▌       | 26/100 [01:13<03:30,  2.84s/it, best=0.7292, head_lr=8.3e-04, lora_lr=8.3e-05, loss=0.7042, val_f1=0.6921]

done model=biomedclip k=16 seed=1 best_epoch=9 best_val_f1=0.7292 test_acc=0.6316 test_f1=0.6241 test_auc=0.8503

biomedclip k=16 seed=2:  43%|████▎     | 43/100 [01:57<02:36,  2.74s/it, best=0.7550, head_lr=5.9e-04, lora_lr=5.9e-05, loss=0.3994, val_f1=0.7175]

done model=biomedclip k=16 seed=2 best_epoch=26 best_val_f1=0.7550 test_acc=0.6632 test_f1=0.6705 test_auc=0.8197

biomedclip k=16 seed=3:  35%|███▌      | 35/100 [01:38<03:03,  2.82s/it, best=0.7315, head_lr=7.1e-04, lora_lr=7.1e-05, loss=0.5641, val_f1=0.7200]

done model=biomedclip k=16 seed=3 best_epoch=18 best_val_f1=0.7315 test_acc=0.7053 test_f1=0.7091 test_auc=0.8761

biomedclip k=16 seed=4:  44%|████▍     | 44/100 [02:02<02:36,  2.79s/it, best=0.8050, head_lr=5.8e-04, lora_lr=5.8e-05, loss=0.3909, val_f1=0.7614]

done model=biomedclip k=16 seed=4 best_epoch=27 best_val_f1=0.8050 test_acc=0.7368 test_f1=0.7405 test_auc=0.8910

biomedclip k=16 seed=5:  37%|███▋      | 37/100 [01:44<02:58,  2.83s/it, best=0.7881, head_lr=6.8e-04, lora_lr=6.8e-05, loss=0.4444, val_f1=0.7619]

done model=biomedclip k=16 seed=5 best_epoch=20 best_val_f1=0.7881 test_acc=0.7263 test_f1=0.7344 test_auc=0.8673

biomedclip k=16 seed=6:  35%|███▌      | 35/100 [01:38<03:02,  2.80s/it, best=0.7442, head_lr=7.1e-04, lora_lr=7.1e-05, loss=0.5329, val_f1=0.7240]

done model=biomedclip k=16 seed=6 best_epoch=18 best_val_f1=0.7442 test_acc=0.7474 test_f1=0.7407 test_auc=0.8747

biomedclip k=16 seed=7:  53%|█████▎    | 53/100 [02:29<02:12,  2.82s/it, best=0.7576, head_lr=4.4e-04, lora_lr=4.4e-05, loss=0.2983, val_f1=0.7291]

done model=biomedclip k=16 seed=7 best_epoch=36 best_val_f1=0.7576 test_acc=0.8316 test_f1=0.8246 test_auc=0.9282

biomedclip k=16 seed=8:  40%|████      | 40/100 [01:50<02:46,  2.77s/it, best=0.7682, head_lr=6.4e-04, lora_lr=6.4e-05, loss=0.4585, val_f1=0.7112]

done model=biomedclip k=16 seed=8 best_epoch=23 best_val_f1=0.7682 test_acc=0.7684 test_f1=0.7572 test_auc=0.8809

biomedclip k=16 seed=9:  52%|█████▏    | 52/100 [02:22<02:11,  2.75s/it, best=0.7775, head_lr=4.5e-04, lora_lr=4.5e-05, loss=0.3289, val_f1=0.7557]

done model=biomedclip k=16 seed=9 best_epoch=35 best_val_f1=0.7775 test_acc=0.7368 test_f1=0.7390 test_auc=0.8931

biomedclip k=16 seed=10:  40%|████      | 40/100 [01:49<02:44,  2.74s/it, best=0.7731, head_lr=6.4e-04, lora_lr=6.4e-05, loss=0.4657, val_f1=0.7340]

done model=biomedclip k=16 seed=10 best_epoch=23 best_val_f1=0.7731 test_acc=0.7474 test_f1=0.7521 test_auc=0.9051

biomedclip k=32 seed=1:  80%|████████  | 80/100 [05:14<01:18,  3.93s/it, best=0.7821, head_lr=8.7e-05, lora_lr=8.7e-06, loss=0.1182, val_f1=0.7729]

done model=biomedclip k=32 seed=1 best_epoch=63 best_val_f1=0.7821 test_acc=0.8105 test_f1=0.8284 test_auc=0.8975

biomedclip k=32 seed=2:  31%|███       | 31/100 [02:06<04:41,  4.08s/it, best=0.7855, head_lr=7.7e-04, lora_lr=7.7e-05, loss=0.3840, val_f1=0.7664]

done model=biomedclip k=32 seed=2 best_epoch=14 best_val_f1=0.7855 test_acc=0.7579 test_f1=0.7562 test_auc=0.8810

biomedclip k=32 seed=3:  63%|██████▎   | 63/100 [04:14<02:29,  4.03s/it, best=0.7574, head_lr=2.9e-04, lora_lr=2.9e-05, loss=0.0958, val_f1=0.7503]

done model=biomedclip k=32 seed=3 best_epoch=46 best_val_f1=0.7574 test_acc=0.6947 test_f1=0.6990 test_auc=0.8949

biomedclip k=32 seed=4:  61%|██████    | 61/100 [04:00<02:34,  3.95s/it, best=0.8588, head_lr=3.2e-04, lora_lr=3.2e-05, loss=0.1268, val_f1=0.7831]

done model=biomedclip k=32 seed=4 best_epoch=44 best_val_f1=0.8588 test_acc=0.7368 test_f1=0.7361 test_auc=0.9313

biomedclip k=32 seed=5:  58%|█████▊    | 58/100 [03:47<02:44,  3.92s/it, best=0.8038, head_lr=3.6e-04, lora_lr=3.6e-05, loss=0.1026, val_f1=0.7811]

done model=biomedclip k=32 seed=5 best_epoch=41 best_val_f1=0.8038 test_acc=0.7895 test_f1=0.7929 test_auc=0.9072

biomedclip k=32 seed=6:  41%|████      | 41/100 [02:47<04:00,  4.08s/it, best=0.8052, head_lr=6.2e-04, lora_lr=6.2e-05, loss=0.2883, val_f1=0.7869]

done model=biomedclip k=32 seed=6 best_epoch=24 best_val_f1=0.8052 test_acc=0.7158 test_f1=0.7205 test_auc=0.8808

biomedclip k=32 seed=7:  44%|████▍     | 44/100 [02:58<03:46,  4.05s/it, best=0.7830, head_lr=5.8e-04, lora_lr=5.8e-05, loss=0.2281, val_f1=0.7616]

done model=biomedclip k=32 seed=7 best_epoch=27 best_val_f1=0.7830 test_acc=0.7579 test_f1=0.7563 test_auc=0.9075

biomedclip k=32 seed=8:  32%|███▏      | 32/100 [02:14<04:45,  4.21s/it, best=0.7822, head_lr=7.5e-04, lora_lr=7.5e-05, loss=0.4105, val_f1=0.7636]

done model=biomedclip k=32 seed=8 best_epoch=15 best_val_f1=0.7822 test_acc=0.7474 test_f1=0.7461 test_auc=0.8927

biomedclip k=32 seed=9:  54%|█████▍    | 54/100 [03:41<03:09,  4.11s/it, best=0.7692, head_lr=4.2e-04, lora_lr=4.2e-05, loss=0.1830, val_f1=0.7295]

done model=biomedclip k=32 seed=9 best_epoch=37 best_val_f1=0.7692 test_acc=0.7053 test_f1=0.7143 test_auc=0.8916

biomedclip k=32 seed=10:  31%|███       | 31/100 [02:07<04:44,  4.13s/it, best=0.7727, head_lr=7.7e-04, lora_lr=7.7e-05, loss=0.4627, val_f1=0.7353]

done model=biomedclip k=32 seed=10 best_epoch=14 best_val_f1=0.7727 test_acc=0.7263 test_f1=0.7377 test_auc=0.8831

LoRA summary:
 k  best_epoch_mean  best_val_macro_f1_mean  best_val_macro_f1_std  test_accuracy_mean  test_accuracy_std  test_macro_f1_mean  test_macro_f1_std  test_auc_mean  test_auc_std
 1             31.7                0.472345               0.098654            0.480000           0.080808            0.432656           0.079574       0.669602      0.087496
 2             29.2                0.542696               0.148860            0.530526           0.137801            0.514386           0.136030       0.718877      0.130848
 4             37.6                0.637319               0.141963            0.612632           0.126977            0.596512           0.144080       0.803095      0.099336
 8             32.3                0.709948               0.050411            0.676842           0.040022            0.665535           0.043271       0.847676      0.025402
16             23.5                0.762942               0.024306            0.729474           0.055044            0.729225           0.053428       0.878630      0.029721
32             32.5                0.790002               0.028152            0.744211           0.036481            0.748729           0.038238       0.896770      0.015492

,k,best_epoch_mean,best_val_macro_f1_mean,best_val_macro_f1_std,test_accuracy_mean,test_accuracy_std,test_macro_f1_mean,test_macro_f1_std,test_auc_mean,test_auc_std
0,1,31.7,0.472345,0.098654,0.480000,0.080808,0.432656,0.079574,0.669602,0.087496
1,2,29.2,0.542696,0.148860,0.530526,0.137801,0.514386,0.136030,0.718877,0.130848
2,4,37.6,0.637319,0.141963,0.612632,0.126977,0.596512,0.144080,0.803095,0.099336
3,8,32.3,0.709948,0.050411,0.676842,0.040022,0.665535,0.043271,0.847676,0.025402
4,16,23.5,0.762942,0.024306,0.729474,0.055044,0.729225,0.053428,0.878630,0.029721
5,32,32.5,0.790002,0.028152,0.744211,0.036481,0.748729,0.038238,0.896770,0.015492

Few-Shot LoRA Fine-Tuning using UniMed-CLIP ViT-B/16

In [16]:
# Run LoRA training for UniMed-CLIP.
args = get_args([])
args.console_log = False
args.show_progress = True
args.log_epochs = False
args.log_train_metrics = False

args.model_name = 'unimedclip'
args.device = device
args.project_root = str(project_root)
args.num_classes = len(busi_classes)
args.encoder = 'vision'

# Training knobs.
args.epochs = 100
args.batch_size = 8
args.accumulation_steps = 4
args.patience = 18
args.grad_clip = 1.0

# Optimizer knobs.
# The optimizer uses head_lr and lora_lr, not args.lr.
args.lr = 1e-4
args.head_lr = 1e-3
args.lora_lr = 1e-4
args.lr_min = 1e-7
args.head_weight_decay = 1e-3
args.lora_weight_decay = 1e-5

# LoRA knobs.
args.lora_layers = None
args.lora_rank = 16
args.lora_alpha = 32
args.lora_dropout = 0.1

# Target q, k, v, and output projection for fair comparison with BiomedCLIP qkv + proj.
args.clip_lora_targets = ['q', 'k', 'v', 'o']

# Use eval preprocessing during LoRA training for a controlled few-shot comparison.
args.use_eval_preprocess_for_train = False

save_dir = lora_base_save_dir / args.model_name

unimedclip_lora_results_df, unimedclip_lora_summary_df = run_kshot_experiments(
    args=args,
    train_df=train_df,
    val_df=val_df,
    test_df=test_df,
    class_names=lora_class_names,
    ks=shots_per_class,
    seeds=seeds,
    save_dir=save_dir,
    support_indices=shared_support_indices,
)

unimedclip_lora_summary_df

LoRA few-shot: model=unimedclip | k=[1, 2, 4, 8, 16, 32] | seeds=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10] | rank=16 | alpha=32 | dropout=0.1 | layers=None

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

injected lora adapters to 12 layers (clip vision encoder)
trainable params: 1,179,648 / 197,083,137

LoRA model check: unimedclip
  trainable vision tensors: 96
  vision trainable params: 1,179,648 / 197,083,137
  classifier trainable params: 1,539
  total trainable params: 1,181,187

unimedclip k=1 seed=1:  42%|████▏     | 42/100 [01:16<01:45,  1.83s/it, best=0.4859, head_lr=6.1e-04, lora_lr=6.1e-05, loss=0.6727, val_f1=0.4839]

done model=unimedclip k=1 seed=1 best_epoch=25 best_val_f1=0.4859 test_acc=0.4211 test_f1=0.3811 test_auc=0.5597

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=1 seed=2:  52%|█████▏    | 52/100 [01:35<01:28,  1.83s/it, best=0.3296, head_lr=4.5e-04, lora_lr=4.5e-05, loss=0.5168, val_f1=0.2909]

done model=unimedclip k=1 seed=2 best_epoch=35 best_val_f1=0.3296 test_acc=0.5895 test_f1=0.4281 test_auc=0.6232

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=1 seed=3:  40%|████      | 40/100 [01:10<01:46,  1.77s/it, best=0.3560, head_lr=6.4e-04, lora_lr=6.4e-05, loss=0.5940, val_f1=0.2980]

done model=unimedclip k=1 seed=3 best_epoch=23 best_val_f1=0.3560 test_acc=0.4000 test_f1=0.3513 test_auc=0.4913

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=1 seed=4:  44%|████▍     | 44/100 [01:21<01:44,  1.86s/it, best=0.4993, head_lr=5.8e-04, lora_lr=5.8e-05, loss=0.5792, val_f1=0.4589]

done model=unimedclip k=1 seed=4 best_epoch=27 best_val_f1=0.4993 test_acc=0.3684 test_f1=0.3377 test_auc=0.5215

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=1 seed=5:  26%|██▌       | 26/100 [00:48<02:17,  1.85s/it, best=0.4093, head_lr=8.3e-04, lora_lr=8.3e-05, loss=0.7965, val_f1=0.3550]

done model=unimedclip k=1 seed=5 best_epoch=9 best_val_f1=0.4093 test_acc=0.3053 test_f1=0.2805 test_auc=0.4969

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=1 seed=6:  46%|████▌     | 46/100 [01:22<01:37,  1.80s/it, best=0.4296, head_lr=5.5e-04, lora_lr=5.5e-05, loss=0.5999, val_f1=0.3514]

done model=unimedclip k=1 seed=6 best_epoch=29 best_val_f1=0.4296 test_acc=0.3789 test_f1=0.3644 test_auc=0.6561

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=1 seed=7:  33%|███▎      | 33/100 [01:00<02:02,  1.82s/it, best=0.3204, head_lr=7.4e-04, lora_lr=7.4e-05, loss=0.7266, val_f1=0.2506]

done model=unimedclip k=1 seed=7 best_epoch=16 best_val_f1=0.3204 test_acc=0.2947 test_f1=0.2983 test_auc=0.5957

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=1 seed=8:  50%|█████     | 50/100 [01:29<01:29,  1.80s/it, best=0.3250, head_lr=4.8e-04, lora_lr=4.8e-05, loss=0.5351, val_f1=0.3019]

done model=unimedclip k=1 seed=8 best_epoch=33 best_val_f1=0.3250 test_acc=0.3579 test_f1=0.2820 test_auc=0.5650

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=1 seed=9:  38%|███▊      | 38/100 [01:08<01:51,  1.80s/it, best=0.4051, head_lr=6.7e-04, lora_lr=6.7e-05, loss=0.7324, val_f1=0.3686]

done model=unimedclip k=1 seed=9 best_epoch=21 best_val_f1=0.4051 test_acc=0.3579 test_f1=0.2850 test_auc=0.5216

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=1 seed=10:  32%|███▏      | 32/100 [00:58<02:03,  1.82s/it, best=0.3201, head_lr=7.5e-04, lora_lr=7.5e-05, loss=0.7094, val_f1=0.3034]

done model=unimedclip k=1 seed=10 best_epoch=15 best_val_f1=0.3201 test_acc=0.2632 test_f1=0.2668 test_auc=0.5783

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=2 seed=1:  35%|███▌      | 35/100 [01:04<01:59,  1.83s/it, best=0.4974, head_lr=7.1e-04, lora_lr=7.1e-05, loss=0.7379, val_f1=0.4479]

done model=unimedclip k=2 seed=1 best_epoch=18 best_val_f1=0.4974 test_acc=0.3053 test_f1=0.2938 test_auc=0.5491

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=2 seed=2:  27%|██▋       | 27/100 [00:50<02:15,  1.86s/it, best=0.5095, head_lr=8.2e-04, lora_lr=8.2e-05, loss=0.8216, val_f1=0.4875]

done model=unimedclip k=2 seed=2 best_epoch=10 best_val_f1=0.5095 test_acc=0.3684 test_f1=0.3656 test_auc=0.5651

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=2 seed=3:  63%|██████▎   | 63/100 [01:54<01:07,  1.81s/it, best=0.3675, head_lr=2.9e-04, lora_lr=2.9e-05, loss=0.5108, val_f1=0.3568]

done model=unimedclip k=2 seed=3 best_epoch=46 best_val_f1=0.3675 test_acc=0.3474 test_f1=0.3197 test_auc=0.4925

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=2 seed=4:  28%|██▊       | 28/100 [00:52<02:14,  1.87s/it, best=0.5733, head_lr=8.1e-04, lora_lr=8.1e-05, loss=0.8294, val_f1=0.5131]

done model=unimedclip k=2 seed=4 best_epoch=11 best_val_f1=0.5733 test_acc=0.4105 test_f1=0.4025 test_auc=0.6069

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=2 seed=5:  25%|██▌       | 25/100 [00:46<02:19,  1.85s/it, best=0.2962, head_lr=8.4e-04, lora_lr=8.4e-05, loss=0.8153, val_f1=0.2933]

done model=unimedclip k=2 seed=5 best_epoch=8 best_val_f1=0.2962 test_acc=0.3053 test_f1=0.2815 test_auc=0.4481

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=2 seed=6:  24%|██▍       | 24/100 [00:44<02:20,  1.85s/it, best=0.4218, head_lr=8.5e-04, lora_lr=8.5e-05, loss=0.8503, val_f1=0.3699]

done model=unimedclip k=2 seed=6 best_epoch=7 best_val_f1=0.4218 test_acc=0.3263 test_f1=0.3141 test_auc=0.4930

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=2 seed=7:  23%|██▎       | 23/100 [00:42<02:22,  1.85s/it, best=0.3885, head_lr=8.6e-04, lora_lr=8.6e-05, loss=0.9040, val_f1=0.3649]

done model=unimedclip k=2 seed=7 best_epoch=6 best_val_f1=0.3885 test_acc=0.3053 test_f1=0.2970 test_auc=0.5617

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=2 seed=8:  30%|███       | 30/100 [00:54<02:07,  1.82s/it, best=0.3091, head_lr=7.8e-04, lora_lr=7.8e-05, loss=0.8425, val_f1=0.2927]

done model=unimedclip k=2 seed=8 best_epoch=13 best_val_f1=0.3091 test_acc=0.5263 test_f1=0.3143 test_auc=0.6180

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=2 seed=9:  30%|███       | 30/100 [00:55<02:08,  1.84s/it, best=0.3704, head_lr=7.8e-04, lora_lr=7.8e-05, loss=0.8035, val_f1=0.2597]

done model=unimedclip k=2 seed=9 best_epoch=13 best_val_f1=0.3704 test_acc=0.3368 test_f1=0.2631 test_auc=0.5793

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=2 seed=10:  53%|█████▎    | 53/100 [01:37<01:26,  1.84s/it, best=0.4443, head_lr=4.4e-04, lora_lr=4.4e-05, loss=0.5472, val_f1=0.4358]

done model=unimedclip k=2 seed=10 best_epoch=36 best_val_f1=0.4443 test_acc=0.4632 test_f1=0.4418 test_auc=0.6705

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=4 seed=1:  42%|████▏     | 42/100 [01:24<01:56,  2.00s/it, best=0.6555, head_lr=6.1e-04, lora_lr=6.1e-05, loss=0.7449, val_f1=0.6256]

done model=unimedclip k=4 seed=1 best_epoch=25 best_val_f1=0.6555 test_acc=0.6211 test_f1=0.5814 test_auc=0.7462

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=4 seed=2:  31%|███       | 31/100 [00:59<02:13,  1.93s/it, best=0.5332, head_lr=7.7e-04, lora_lr=7.7e-05, loss=0.9402, val_f1=0.4437]

done model=unimedclip k=4 seed=2 best_epoch=14 best_val_f1=0.5332 test_acc=0.5158 test_f1=0.4862 test_auc=0.6684

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=4 seed=3:  69%|██████▉   | 69/100 [02:09<00:58,  1.88s/it, best=0.4876, head_lr=2.1e-04, lora_lr=2.1e-05, loss=0.6090, val_f1=0.4446]

done model=unimedclip k=4 seed=3 best_epoch=52 best_val_f1=0.4876 test_acc=0.5895 test_f1=0.4434 test_auc=0.6897

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=4 seed=4:  86%|████████▌ | 86/100 [02:41<00:26,  1.88s/it, best=0.6923, head_lr=4.1e-05, lora_lr=4.2e-06, loss=0.5114, val_f1=0.6823]

done model=unimedclip k=4 seed=4 best_epoch=69 best_val_f1=0.6923 test_acc=0.6316 test_f1=0.6320 test_auc=0.8398

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=4 seed=5:  28%|██▊       | 28/100 [00:52<02:15,  1.88s/it, best=0.2580, head_lr=8.1e-04, lora_lr=8.1e-05, loss=0.9245, val_f1=0.1720]

done model=unimedclip k=4 seed=5 best_epoch=11 best_val_f1=0.2580 test_acc=0.3579 test_f1=0.3019 test_auc=0.5863

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=4 seed=6:  49%|████▉     | 49/100 [01:31<01:35,  1.87s/it, best=0.5743, head_lr=5.0e-04, lora_lr=5.0e-05, loss=0.6680, val_f1=0.4983]

done model=unimedclip k=4 seed=6 best_epoch=32 best_val_f1=0.5743 test_acc=0.5474 test_f1=0.4554 test_auc=0.6972

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=4 seed=7:  74%|███████▍  | 74/100 [02:18<00:48,  1.88s/it, best=0.4691, head_lr=1.5e-04, lora_lr=1.5e-05, loss=0.5956, val_f1=0.4632]

done model=unimedclip k=4 seed=7 best_epoch=57 best_val_f1=0.4691 test_acc=0.4737 test_f1=0.4720 test_auc=0.7567

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=4 seed=8:  81%|████████  | 81/100 [02:31<00:35,  1.88s/it, best=0.5761, head_lr=7.8e-05, lora_lr=7.9e-06, loss=0.5358, val_f1=0.5405]

done model=unimedclip k=4 seed=8 best_epoch=64 best_val_f1=0.5761 test_acc=0.5263 test_f1=0.5215 test_auc=0.7739

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=4 seed=9:  45%|████▌     | 45/100 [01:25<01:44,  1.90s/it, best=0.4820, head_lr=5.6e-04, lora_lr=5.6e-05, loss=0.7535, val_f1=0.4173]

done model=unimedclip k=4 seed=9 best_epoch=28 best_val_f1=0.4820 test_acc=0.5579 test_f1=0.5181 test_auc=0.6822

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=4 seed=10:  77%|███████▋  | 77/100 [02:21<00:42,  1.83s/it, best=0.5568, head_lr=1.1e-04, lora_lr=1.2e-05, loss=0.5255, val_f1=0.5400]

done model=unimedclip k=4 seed=10 best_epoch=60 best_val_f1=0.5568 test_acc=0.6421 test_f1=0.6001 test_auc=0.7971

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=8 seed=1:  36%|███▌      | 36/100 [01:19<02:21,  2.21s/it, best=0.4940, head_lr=7.0e-04, lora_lr=7.0e-05, loss=0.8152, val_f1=0.4426]

done model=unimedclip k=8 seed=1 best_epoch=19 best_val_f1=0.4940 test_acc=0.3684 test_f1=0.3579 test_auc=0.6396

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=8 seed=2:  48%|████▊     | 48/100 [01:44<01:52,  2.17s/it, best=0.4981, head_lr=5.2e-04, lora_lr=5.2e-05, loss=0.6943, val_f1=0.4446]

done model=unimedclip k=8 seed=2 best_epoch=31 best_val_f1=0.4981 test_acc=0.5474 test_f1=0.5442 test_auc=0.7828

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=8 seed=3:  39%|███▉      | 39/100 [01:24<02:12,  2.17s/it, best=0.4196, head_lr=6.5e-04, lora_lr=6.5e-05, loss=0.7771, val_f1=0.3713]

done model=unimedclip k=8 seed=3 best_epoch=22 best_val_f1=0.4196 test_acc=0.5158 test_f1=0.4585 test_auc=0.6306

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=8 seed=4:  89%|████████▉ | 89/100 [03:08<00:23,  2.12s/it, best=0.6702, head_lr=2.5e-05, lora_lr=2.5e-06, loss=0.5110, val_f1=0.6702]

done model=unimedclip k=8 seed=4 best_epoch=72 best_val_f1=0.6702 test_acc=0.6737 test_f1=0.6473 test_auc=0.8531

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=8 seed=5:  47%|████▋     | 47/100 [01:40<01:53,  2.14s/it, best=0.5234, head_lr=5.3e-04, lora_lr=5.3e-05, loss=0.7275, val_f1=0.4782]

done model=unimedclip k=8 seed=5 best_epoch=30 best_val_f1=0.5234 test_acc=0.3895 test_f1=0.3790 test_auc=0.6424

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=8 seed=6:  53%|█████▎    | 53/100 [01:55<01:42,  2.18s/it, best=0.4168, head_lr=4.4e-04, lora_lr=4.4e-05, loss=0.6585, val_f1=0.3696]

done model=unimedclip k=8 seed=6 best_epoch=36 best_val_f1=0.4168 test_acc=0.3684 test_f1=0.3152 test_auc=0.6658

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=8 seed=7:  65%|██████▌   | 65/100 [02:19<01:15,  2.15s/it, best=0.4694, head_lr=2.6e-04, lora_lr=2.6e-05, loss=0.5796, val_f1=0.4495]

done model=unimedclip k=8 seed=7 best_epoch=48 best_val_f1=0.4694 test_acc=0.4211 test_f1=0.3827 test_auc=0.5669

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=8 seed=8:  22%|██▏       | 22/100 [00:48<02:51,  2.20s/it, best=0.4378, head_lr=8.8e-04, lora_lr=8.8e-05, loss=0.9595, val_f1=0.3855]

done model=unimedclip k=8 seed=8 best_epoch=5 best_val_f1=0.4378 test_acc=0.5053 test_f1=0.3914 test_auc=0.5720

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=8 seed=9:  82%|████████▏ | 82/100 [02:56<00:38,  2.16s/it, best=0.5349, head_lr=7.0e-05, lora_lr=7.1e-06, loss=0.5387, val_f1=0.5309]

done model=unimedclip k=8 seed=9 best_epoch=65 best_val_f1=0.5349 test_acc=0.4842 test_f1=0.4808 test_auc=0.7353

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=8 seed=10:  55%|█████▌    | 55/100 [01:59<01:37,  2.17s/it, best=0.4093, head_lr=4.1e-04, lora_lr=4.1e-05, loss=0.7177, val_f1=0.3917]

done model=unimedclip k=8 seed=10 best_epoch=38 best_val_f1=0.4093 test_acc=0.5368 test_f1=0.5057 test_auc=0.5948

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=16 seed=1:  45%|████▌     | 45/100 [02:04<02:31,  2.76s/it, best=0.6275, head_lr=5.6e-04, lora_lr=5.6e-05, loss=0.3884, val_f1=0.5391]

done model=unimedclip k=16 seed=1 best_epoch=28 best_val_f1=0.6275 test_acc=0.5684 test_f1=0.5536 test_auc=0.7441

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=16 seed=2:  50%|█████     | 50/100 [02:23<02:23,  2.88s/it, best=0.7435, head_lr=4.8e-04, lora_lr=4.8e-05, loss=0.3731, val_f1=0.7111]

done model=unimedclip k=16 seed=2 best_epoch=33 best_val_f1=0.7435 test_acc=0.6632 test_f1=0.6574 test_auc=0.8397

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=16 seed=3:  61%|██████    | 61/100 [02:56<01:52,  2.89s/it, best=0.5850, head_lr=3.2e-04, lora_lr=3.2e-05, loss=0.3018, val_f1=0.4888]

done model=unimedclip k=16 seed=3 best_epoch=44 best_val_f1=0.5850 test_acc=0.6000 test_f1=0.5806 test_auc=0.8044

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=16 seed=4:  53%|█████▎    | 53/100 [02:34<02:17,  2.92s/it, best=0.7214, head_lr=4.4e-04, lora_lr=4.4e-05, loss=0.3912, val_f1=0.6424]

done model=unimedclip k=16 seed=4 best_epoch=36 best_val_f1=0.7214 test_acc=0.6526 test_f1=0.6152 test_auc=0.8381

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=16 seed=5:  54%|█████▍    | 54/100 [02:37<02:13,  2.91s/it, best=0.4480, head_lr=4.2e-04, lora_lr=4.2e-05, loss=0.5603, val_f1=0.3353]

done model=unimedclip k=16 seed=5 best_epoch=37 best_val_f1=0.4480 test_acc=0.4947 test_f1=0.3846 test_auc=0.6912

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=16 seed=6:  43%|████▎     | 43/100 [02:04<02:45,  2.90s/it, best=0.5574, head_lr=5.9e-04, lora_lr=5.9e-05, loss=0.5623, val_f1=0.5093]

done model=unimedclip k=16 seed=6 best_epoch=26 best_val_f1=0.5574 test_acc=0.6000 test_f1=0.4729 test_auc=0.8050

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=16 seed=7:  59%|█████▉    | 59/100 [02:51<01:59,  2.90s/it, best=0.6868, head_lr=3.5e-04, lora_lr=3.5e-05, loss=0.3172, val_f1=0.6488]

done model=unimedclip k=16 seed=7 best_epoch=42 best_val_f1=0.6868 test_acc=0.6421 test_f1=0.6190 test_auc=0.8702

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=16 seed=8:  50%|█████     | 50/100 [02:24<02:24,  2.89s/it, best=0.5934, head_lr=4.8e-04, lora_lr=4.8e-05, loss=0.3513, val_f1=0.5779]

done model=unimedclip k=16 seed=8 best_epoch=33 best_val_f1=0.5934 test_acc=0.6947 test_f1=0.6746 test_auc=0.8437

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=16 seed=9:  53%|█████▎    | 53/100 [02:35<02:17,  2.93s/it, best=0.5666, head_lr=4.4e-04, lora_lr=4.4e-05, loss=0.3262, val_f1=0.4963]

done model=unimedclip k=16 seed=9 best_epoch=36 best_val_f1=0.5666 test_acc=0.5158 test_f1=0.5102 test_auc=0.8206

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=16 seed=10:  33%|███▎      | 33/100 [01:37<03:18,  2.96s/it, best=0.4637, head_lr=7.4e-04, lora_lr=7.4e-05, loss=0.6295, val_f1=0.3463]

done model=unimedclip k=16 seed=10 best_epoch=16 best_val_f1=0.4637 test_acc=0.5158 test_f1=0.5046 test_auc=0.6823

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=32 seed=1:  22%|██▏       | 22/100 [01:34<05:35,  4.30s/it, best=0.4844, head_lr=8.8e-04, lora_lr=8.8e-05, loss=0.6889, val_f1=0.4833]

done model=unimedclip k=32 seed=1 best_epoch=5 best_val_f1=0.4844 test_acc=0.4316 test_f1=0.4209 test_auc=0.6501

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=32 seed=2:  47%|████▋     | 47/100 [03:15<03:40,  4.16s/it, best=0.8050, head_lr=5.3e-04, lora_lr=5.3e-05, loss=0.2052, val_f1=0.7753]

done model=unimedclip k=32 seed=2 best_epoch=30 best_val_f1=0.8050 test_acc=0.7158 test_f1=0.7255 test_auc=0.9113

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=32 seed=3:  38%|███▊      | 38/100 [02:34<04:11,  4.06s/it, best=0.5990, head_lr=6.7e-04, lora_lr=6.7e-05, loss=0.2968, val_f1=0.5458]

done model=unimedclip k=32 seed=3 best_epoch=21 best_val_f1=0.5990 test_acc=0.4632 test_f1=0.4543 test_auc=0.7655

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=32 seed=4:  47%|████▋     | 47/100 [03:06<03:30,  3.97s/it, best=0.6528, head_lr=5.3e-04, lora_lr=5.3e-05, loss=0.1837, val_f1=0.5782]

done model=unimedclip k=32 seed=4 best_epoch=30 best_val_f1=0.6528 test_acc=0.6105 test_f1=0.6056 test_auc=0.8292

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=32 seed=5:  62%|██████▏   | 62/100 [04:04<02:30,  3.95s/it, best=0.7702, head_lr=3.0e-04, lora_lr=3.0e-05, loss=0.1099, val_f1=0.7702]

done model=unimedclip k=32 seed=5 best_epoch=45 best_val_f1=0.7702 test_acc=0.7789 test_f1=0.7754 test_auc=0.8911

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=32 seed=6:  64%|██████▍   | 64/100 [04:13<02:22,  3.97s/it, best=0.7710, head_lr=2.7e-04, lora_lr=2.7e-05, loss=0.1105, val_f1=0.7668]

done model=unimedclip k=32 seed=6 best_epoch=47 best_val_f1=0.7710 test_acc=0.7053 test_f1=0.7129 test_auc=0.8863

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=32 seed=7:  74%|███████▍  | 74/100 [04:51<01:42,  3.94s/it, best=0.6845, head_lr=1.5e-04, lora_lr=1.5e-05, loss=0.0819, val_f1=0.6556]

done model=unimedclip k=32 seed=7 best_epoch=57 best_val_f1=0.6845 test_acc=0.5789 test_f1=0.5768 test_auc=0.8337

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=32 seed=8:  20%|██        | 20/100 [01:21<05:24,  4.05s/it, best=0.6058, head_lr=9.0e-04, lora_lr=9.0e-05, loss=0.7067, val_f1=0.5823]

done model=unimedclip k=32 seed=8 best_epoch=3 best_val_f1=0.6058 test_acc=0.6421 test_f1=0.5970 test_auc=0.7609

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=32 seed=9:  62%|██████▏   | 62/100 [04:03<02:29,  3.93s/it, best=0.6660, head_lr=3.0e-04, lora_lr=3.0e-05, loss=0.1638, val_f1=0.6551]

done model=unimedclip k=32 seed=9 best_epoch=45 best_val_f1=0.6660 test_acc=0.7263 test_f1=0.7086 test_auc=0.8829

[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.pooler.dense.weight                   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
bert.pooler.dense.bias                     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
unimedclip k=32 seed=10:  85%|████████▌ | 85/100 [05:33<00:58,  3.92s/it, best=0.7267, head_lr=4.8e-05, lora_lr=4.9e-06, loss=0.0766, val_f1=0.7267]

done model=unimedclip k=32 seed=10 best_epoch=68 best_val_f1=0.7267 test_acc=0.7368 test_f1=0.7416 test_auc=0.9043

LoRA summary:
 k  best_epoch_mean  best_val_macro_f1_mean  best_val_macro_f1_std  test_accuracy_mean  test_accuracy_std  test_macro_f1_mean  test_macro_f1_std  test_auc_mean  test_auc_std
 1             23.3                0.388025               0.068330            0.373684           0.090176            0.327534           0.053376       0.560920      0.054279
 2             16.8                0.417800               0.089358            0.369474           0.075165            0.329347           0.056603       0.558429      0.066523
 4             41.2                0.528493               0.119565            0.546316           0.085725            0.501206           0.094453       0.723770      0.073408
 8             36.6                0.487357               0.078601            0.481053           0.096482            0.446271           0.100801       0.668345      0.094073
16             33.1                0.599337               0.099162            0.594737           0.069514            0.557264           0.090337       0.793937      0.065648
32             35.1                0.676532               0.097404            0.638947           0.118059            0.631857           0.122407       0.831532      0.083745

,k,best_epoch_mean,best_val_macro_f1_mean,best_val_macro_f1_std,test_accuracy_mean,test_accuracy_std,test_macro_f1_mean,test_macro_f1_std,test_auc_mean,test_auc_std
0,1,23.3,0.388025,0.068330,0.373684,0.090176,0.327534,0.053376,0.560920,0.054279
1,2,16.8,0.417800,0.089358,0.369474,0.075165,0.329347,0.056603,0.558429,0.066523
2,4,41.2,0.528493,0.119565,0.546316,0.085725,0.501206,0.094453,0.723770,0.073408
3,8,36.6,0.487357,0.078601,0.481053,0.096482,0.446271,0.100801,0.668345,0.094073
4,16,33.1,0.599337,0.099162,0.594737,0.069514,0.557264,0.090337,0.793937,0.065648
5,32,35.1,0.676532,0.097404,0.638947,0.118059,0.631857,0.122407,0.831532,0.083745